const mockDataLakeProductRecommendationByUser = [
  {
    id: 1,
    data: [
      {
        item: [
          'CDS26735481',
          'CDS23103283',
          'CDS23290266',
          'CDS18735444',
          'CDS17278072',
          'CDS8451903',
          'MKP0239946',
          'CDS23803220',
          'CDS16968929',
          'CDS3684511',
          'CDS21537417',
          'CDS12298600',
          'MKP0025628',
          'CDS24926973',
          'CDS18361575',
          'CDS14284212',
          'CDS18427097',
          'CDS23068711',
          'CDS21167539',
          'CDS19257532',
          'CDS3551028',
          'MKP0025624',
          'CDS12075317',
          'CDS21004155',
          'MKP0254715',
          'CDS14116568',
          'CDS13289942',
          'CDS23282421',
        ],
      },
    ],
  },
];

const mockDataLakeAppProductRecommendationByUser = [
  {
    id: 1,
    data: [
      {
        item: ['CDS26735481'],
      },
    ],
  },
];

const mockProductRecommendedCS = [
  {
    id: '180592',
    name: 'รองเท้าลำลอง สีขาว - น้ำเงิน ไซส์ 6',
    type: 'simple',
    sku: 'CDS17278072',
    urlKey: 'onitsuka-tiger-casual-shoes-white-blue-size-6-cds17278072',
    createdAt: '2018-10-03T06:07:56.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 3180,
      final: 3180,
      discount: null,
    },
    brand: {
      id: '641',
      name: 'Onitsuka Tiger',
      urlKey: 'onitsuka-tiger',
    },
    mediaGallery: [],
    breadcrumbs: [
      {
        id: '3053',
        title: 'ผู้ชาย',
        urlKey: 'men',
        level: 1,
      },
      {
        id: '4677',
        title: 'รองเท้า',
        urlKey: 'men/shop-by-style/casual-2/shoes-11',
        level: 4,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 128,
      redeemPoint: 25440,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: null,
    flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'ขาว - น้ำเงิน',
      },
      {
        id: 'size',
        label: '6',
      },
    ],
    options: [],
  },
  {
    id: '82373',
    name: 'แผ่นซับน้ำนมผิวหน้ารังผึ้ง 60',
    type: 'simple',
    sku: 'CDS8451903',
    urlKey: 'pigeon-60-cds8451903',
    createdAt: '2018-08-14T09:52:58.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 189,
      final: 189,
      discount: {
        amount: 0,
        percentage: 0,
        effectiveDateRange: null,
      },
    },
    brand: {
      id: '698',
      name: 'PIGEON',
      urlKey: 'pigeon',
    },
    mediaGallery: [
      {
        id: '978449',
        title: 'แผ่นซับน้ำนมผิวหน้ารังผึ้ง 60',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/c/d/cds8451903.jpg',
        type: 'IMAGE',
        types: ['image', 'small_image', 'thumbnail', 'swatch_image'],
      },
    ],
    breadcrumbs: [],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 8,
      redeemPoint: 1512,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/c/d/cds8451903.jpg',
    flags: ['IN_STOCK', 'ONLINE_SALABLE', 'OFFLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'Mat Kis',
      },
      {
        id: 'size',
        label: '75 cm',
      },
    ],
    options: [],
  },
  {
    id: '68355',
    name: 'หม้อทอดไฟฟ้า ขนาด 800 กรัม สีดำ',
    type: 'simple',
    sku: 'CDS3551028',
    urlKey: 'philips-avance-collection-airfryer-800-black-cds3551028',
    createdAt: '2018-08-14T08:55:31.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 7990,
      final: 7990,
      discount: {
        amount: 0,
        percentage: 0,
        effectiveDateRange: null,
      },
    },
    brand: {
      id: '692',
      name: 'PHILIPS',
      urlKey: 'philips',
    },
    mediaGallery: [],
    breadcrumbs: [
      {
        id: '5728',
        title: 'home',
        urlKey: 'root/home',
        level: 2,
      },
      {
        id: '5746',
        title: 'cooking_dining',
        urlKey: 'root/home/cooking-dining',
        level: 3,
      },
      {
        id: '5747',
        title: 'cooking_appliances',
        urlKey: 'root/home/cooking-dining/cooking-appliances',
        level: 4,
      },
      {
        id: '5764',
        title: 'fryers',
        urlKey: 'root/home/cooking-dining/cooking-appliances/fryers',
        level: 5,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 320,
      redeemPoint: 63920,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: null,
    flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['STANDARD_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'Fair Ochre',
      },
      {
        id: 'size',
        label: '65 ซม.',
      },
    ],
    options: [],
  },
  {
    id: '51908',
    name: 'เตารีดแรงดันไอน้ำ',
    type: 'simple',
    sku: 'CDS12075317',
    urlKey: 'philips-fast-care-steam-generator-gc7703-cds12075317',
    createdAt: '2018-08-14T07:49:55.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 11990,
      final: 11990,
      discount: {
        amount: 0,
        percentage: 0,
        effectiveDateRange: null,
      },
    },
    brand: {
      id: '692',
      name: 'PHILIPS',
      urlKey: 'philips',
    },
    mediaGallery: [
      {
        id: '137168',
        title: 'เตารีดแรงดันไอน้ำ',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
        type: 'IMAGE',
        types: ['image', 'small_image', 'thumbnail'],
      },
      {
        id: '137169',
        title: 'เตารีดแรงดันไอน้ำ',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317_x2.jpg',
        type: 'IMAGE',
        types: [],
      },
    ],
    breadcrumbs: [
      {
        id: '5728',
        title: 'home',
        urlKey: 'root/home',
        level: 2,
      },
      {
        id: '5854',
        title: 'laundry_cleaning_storages',
        urlKey: 'root/home/laundry-cleaning-storages',
        level: 3,
      },
      {
        id: '5856',
        title: 'irons_equipments',
        urlKey: 'root/home/laundry-cleaning-storages/irons-equipments',
        level: 4,
      },
      {
        id: '5857',
        title: 'irons',
        urlKey: 'root/home/laundry-cleaning-storages/irons-equipments/irons',
        level: 5,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 480,
      redeemPoint: 95920,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
    flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'เขียว - ชมพู',
      },
      {
        id: 'size',
        label: '65 ซม.',
      },
    ],
    options: [],
  },
  {
    id: '98169',
    name: 'PIGEON เบบี้ไวพส์คาโมมายล์ รุ่น 3PG0305850600 6 ห่อแถม 3 ห่อ',
    type: 'simple',
    sku: 'CDS14116568',
    urlKey: 'pigeon-pigeon-3pg0305850600-6-3-cds14116568',
    createdAt: '2018-08-14T10:56:47.000Z',
    promotionTag: '10138',
    collectionName: null,
    priceSummary: {
      original: 999,
      final: 999,
      discount: null,
    },
    brand: {
      id: '698',
      name: 'PIGEON',
      urlKey: 'pigeon',
    },
    mediaGallery: [
      {
        id: '235082',
        title: 'PIGEON เบบี้ไวพส์คาโมมายล์ รุ่น 3PG0305850600 6 ห่อแถม 3 ห่อ',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS14116568.jpg',
        type: 'IMAGE',
        types: ['image', 'small_image', 'thumbnail'],
      },
    ],
    breadcrumbs: [
      {
        id: '7023',
        title: 'Nike test',
        urlKey: 'nike-test',
        level: 1,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 40,
      redeemPoint: 7992,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
      {
        id: '..',
        title: '..',
        description: '..',
        effectiveDateRange: {
          from: '2020-06-04T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS14116568.jpg',
    flags: ['IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'เขียว - ชมพู',
      },
      {
        id: 'size',
        label: '65 ซม.',
      },
    ],
    options: [],
  },
  {
    id: '80816',
    name: 'BOTTLE NATURAL 125ML TWIN',
    type: 'simple',
    sku: 'CDS13289942',
    urlKey: 'philips-philips-avent-natural-feeding-bottle-024723-size-125-ml-pack-2-cds13289942',
    createdAt: '2018-08-14T09:46:44.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 790,
      final: 790,
      discount: {
        amount: 0,
        percentage: 0,
        effectiveDateRange: null,
      },
    },
    brand: {
      id: '692',
      name: 'PHILIPS',
      urlKey: 'philips',
    },
    mediaGallery: [
      {
        id: '199279',
        title: 'BOTTLE NATURAL 125ML TWIN',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS13289942.jpg',
        type: 'IMAGE',
        types: ['image', 'small_image', 'thumbnail'],
      },
    ],
    breadcrumbs: [
      {
        id: '7023',
        title: 'Nike test',
        urlKey: 'nike-test',
        level: 1,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 32,
      redeemPoint: 6320,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: {
      totalVoteCount: 5,
      average: 3.6,
    },
    shortDescription: '',
    description: '',
    thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS13289942.jpg',
    flags: [
      'NEW',
      'ONLY_AT_CENTRAL',
      'ONLINE_EXCLUSIVE',
      'IN_STOCK',
      'ONLINE_SALABLE',
      'OFFLINE_SALABLE',
      'SHOW_PRODUCT_ORIGINAL_PRICE',
    ],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: [
      'STANDARD_PICK_UP',
      'TWO_HOURS_PICK_UP',
      'STANDARD_DELIVERY',
      'SAME_DAY_DELIVERY',
      'NEXT_DAY_DELIVERY',
    ],
    paymentMethods: [],
    links: {
      crossSellSKUs: [],
      upSellSKUs: [],
      relatedSKUs: ['CDS10781692', 'CDS10786277', 'CDS10781791'],
      breadcrumbs: [],
      crossSell: [],
      upSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color',
        label: 'ขาว',
      },
      {
        id: 'color_shade_name',
        label: ' ',
      },
      {
        id: 'size',
        label: '55 cm',
      },
    ],
    options: [],
  },
];

const mockProductsResult = {
  totalCount: 6,
  products: [
    {
      id: '180592',
      name: 'รองเท้าลำลอง สีขาว - น้ำเงิน ไซส์ 6',
      type: 'simple',
      sku: 'CDS17278072',
      urlKey: 'onitsuka-tiger-casual-shoes-white-blue-size-6-cds17278072',
      createdAt: '2018-10-03T06:07:56.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 3180,
        final: 3180,
        discount: null,
      },
      brand: {
        id: '641',
        name: 'Onitsuka Tiger',
        urlKey: 'onitsuka-tiger',
      },
      mediaGallery: [],
      breadcrumbs: [
        {
          id: '3053',
          title: 'ผู้ชาย',
          urlKey: 'men',
          level: 1,
        },
        {
          id: '4677',
          title: 'รองเท้า',
          urlKey: 'men/shop-by-style/casual-2/shoes-11',
          level: 4,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 128,
        redeemPoint: 25440,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: null,
      flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'ขาว - น้ำเงิน',
        },
        {
          id: 'size',
          label: '6',
        },
      ],
      options: [],
    },
    {
      id: '82373',
      name: 'แผ่นซับน้ำนมผิวหน้ารังผึ้ง 60',
      type: 'simple',
      sku: 'CDS8451903',
      urlKey: 'pigeon-60-cds8451903',
      createdAt: '2018-08-14T09:52:58.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 189,
        final: 189,
        discount: {
          amount: 0,
          percentage: 0,
          effectiveDateRange: null,
        },
      },
      brand: {
        id: '698',
        name: 'PIGEON',
        urlKey: 'pigeon',
      },
      mediaGallery: [
        {
          id: '978449',
          title: 'แผ่นซับน้ำนมผิวหน้ารังผึ้ง 60',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/c/d/cds8451903.jpg',
          type: 'IMAGE',
          types: ['image', 'small_image', 'thumbnail', 'swatch_image'],
        },
      ],
      breadcrumbs: [],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 8,
        redeemPoint: 1512,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/c/d/cds8451903.jpg',
      flags: ['IN_STOCK', 'ONLINE_SALABLE', 'OFFLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'Mat Kis',
        },
        {
          id: 'size',
          label: '75 cm',
        },
      ],
      options: [],
    },
    {
      id: '68355',
      name: 'หม้อทอดไฟฟ้า ขนาด 800 กรัม สีดำ',
      type: 'simple',
      sku: 'CDS3551028',
      urlKey: 'philips-avance-collection-airfryer-800-black-cds3551028',
      createdAt: '2018-08-14T08:55:31.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 7990,
        final: 7990,
        discount: {
          amount: 0,
          percentage: 0,
          effectiveDateRange: null,
        },
      },
      brand: {
        id: '692',
        name: 'PHILIPS',
        urlKey: 'philips',
      },
      mediaGallery: [],
      breadcrumbs: [
        {
          id: '5728',
          title: 'home',
          urlKey: 'root/home',
          level: 2,
        },
        {
          id: '5746',
          title: 'cooking_dining',
          urlKey: 'root/home/cooking-dining',
          level: 3,
        },
        {
          id: '5747',
          title: 'cooking_appliances',
          urlKey: 'root/home/cooking-dining/cooking-appliances',
          level: 4,
        },
        {
          id: '5764',
          title: 'fryers',
          urlKey: 'root/home/cooking-dining/cooking-appliances/fryers',
          level: 5,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 320,
        redeemPoint: 63920,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: null,
      flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['STANDARD_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'Fair Ochre',
        },
        {
          id: 'size',
          label: '65 ซม.',
        },
      ],
      options: [],
    },
    {
      id: '51908',
      name: 'เตารีดแรงดันไอน้ำ',
      type: 'simple',
      sku: 'CDS12075317',
      urlKey: 'philips-fast-care-steam-generator-gc7703-cds12075317',
      createdAt: '2018-08-14T07:49:55.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 11990,
        final: 11990,
        discount: {
          amount: 0,
          percentage: 0,
          effectiveDateRange: null,
        },
      },
      brand: {
        id: '692',
        name: 'PHILIPS',
        urlKey: 'philips',
      },
      mediaGallery: [
        {
          id: '137168',
          title: 'เตารีดแรงดันไอน้ำ',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
          type: 'IMAGE',
          types: ['image', 'small_image', 'thumbnail'],
        },
        {
          id: '137169',
          title: 'เตารีดแรงดันไอน้ำ',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317_x2.jpg',
          type: 'IMAGE',
          types: [],
        },
      ],
      breadcrumbs: [
        {
          id: '5728',
          title: 'home',
          urlKey: 'root/home',
          level: 2,
        },
        {
          id: '5854',
          title: 'laundry_cleaning_storages',
          urlKey: 'root/home/laundry-cleaning-storages',
          level: 3,
        },
        {
          id: '5856',
          title: 'irons_equipments',
          urlKey: 'root/home/laundry-cleaning-storages/irons-equipments',
          level: 4,
        },
        {
          id: '5857',
          title: 'irons',
          urlKey: 'root/home/laundry-cleaning-storages/irons-equipments/irons',
          level: 5,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 480,
        redeemPoint: 95920,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
      flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'เขียว - ชมพู',
        },
        {
          id: 'size',
          label: '65 ซม.',
        },
      ],
      options: [],
    },
    {
      id: '98169',
      name: 'PIGEON เบบี้ไวพส์คาโมมายล์ รุ่น 3PG0305850600 6 ห่อแถม 3 ห่อ',
      type: 'simple',
      sku: 'CDS14116568',
      urlKey: 'pigeon-pigeon-3pg0305850600-6-3-cds14116568',
      createdAt: '2018-08-14T10:56:47.000Z',
      promotionTag: '10138',
      collectionName: null,
      priceSummary: {
        original: 999,
        final: 999,
        discount: null,
      },
      brand: {
        id: '698',
        name: 'PIGEON',
        urlKey: 'pigeon',
      },
      mediaGallery: [
        {
          id: '235082',
          title: 'PIGEON เบบี้ไวพส์คาโมมายล์ รุ่น 3PG0305850600 6 ห่อแถม 3 ห่อ',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS14116568.jpg',
          type: 'IMAGE',
          types: ['image', 'small_image', 'thumbnail'],
        },
      ],
      breadcrumbs: [
        {
          id: '7023',
          title: 'Nike test',
          urlKey: 'nike-test',
          level: 1,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 40,
        redeemPoint: 7992,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
        {
          id: '..',
          title: '..',
          description: '..',
          effectiveDateRange: {
            from: '2020-06-04T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS14116568.jpg',
      flags: ['IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'เขียว - ชมพู',
        },
        {
          id: 'size',
          label: '65 ซม.',
        },
      ],
      options: [],
    },
    {
      id: '80816',
      name: 'BOTTLE NATURAL 125ML TWIN',
      type: 'simple',
      sku: 'CDS13289942',
      urlKey: 'philips-philips-avent-natural-feeding-bottle-024723-size-125-ml-pack-2-cds13289942',
      createdAt: '2018-08-14T09:46:44.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 790,
        final: 790,
        discount: {
          amount: 0,
          percentage: 0,
          effectiveDateRange: null,
        },
      },
      brand: {
        id: '692',
        name: 'PHILIPS',
        urlKey: 'philips',
      },
      mediaGallery: [
        {
          id: '199279',
          title: 'BOTTLE NATURAL 125ML TWIN',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS13289942.jpg',
          type: 'IMAGE',
          types: ['image', 'small_image', 'thumbnail'],
        },
      ],
      breadcrumbs: [
        {
          id: '7023',
          title: 'Nike test',
          urlKey: 'nike-test',
          level: 1,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 32,
        redeemPoint: 6320,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: {
        totalVoteCount: 5,
        average: 3.6,
      },
      shortDescription: '',
      description: '',
      thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS13289942.jpg',
      flags: [
        'NEW',
        'ONLY_AT_CENTRAL',
        'ONLINE_EXCLUSIVE',
        'IN_STOCK',
        'ONLINE_SALABLE',
        'OFFLINE_SALABLE',
        'SHOW_PRODUCT_ORIGINAL_PRICE',
      ],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: [
        'STANDARD_PICK_UP',
        'TWO_HOURS_PICK_UP',
        'STANDARD_DELIVERY',
        'SAME_DAY_DELIVERY',
        'NEXT_DAY_DELIVERY',
      ],
      paymentMethods: [],
      links: {
        crossSellSKUs: [],
        upSellSKUs: [],
        relatedSKUs: ['CDS10781692', 'CDS10786277', 'CDS10781791'],
        breadcrumbs: [],
        crossSell: [],
        upSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color',
          label: 'ขาว',
        },
        {
          id: 'color_shade_name',
          label: ' ',
        },
        {
          id: 'size',
          label: '55 cm',
        },
      ],
      options: [],
    },
  ],
  filters: [],
  sorts: [],
};

const mockProductRecommendedCSLimit2 = [
  {
    id: '68355',
    name: 'หม้อทอดไฟฟ้า ขนาด 800 กรัม สีดำ',
    type: 'simple',
    sku: 'CDS3551028',
    urlKey: 'philips-avance-collection-airfryer-800-black-cds3551028',
    createdAt: '2018-08-14T08:55:31.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 7990,
      final: 7990,
      discount: {
        amount: 0,
        percentage: 0,
        effectiveDateRange: null,
      },
    },
    brand: {
      id: '692',
      name: 'PHILIPS',
      urlKey: 'philips',
    },
    mediaGallery: [],
    breadcrumbs: [
      {
        id: '5728',
        title: 'home',
        urlKey: 'root/home',
        level: 2,
      },
      {
        id: '5746',
        title: 'cooking_dining',
        urlKey: 'root/home/cooking-dining',
        level: 3,
      },
      {
        id: '5747',
        title: 'cooking_appliances',
        urlKey: 'root/home/cooking-dining/cooking-appliances',
        level: 4,
      },
      {
        id: '5764',
        title: 'fryers',
        urlKey: 'root/home/cooking-dining/cooking-appliances/fryers',
        level: 5,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 320,
      redeemPoint: 63920,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: null,
    flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['STANDARD_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'Fair Ochre',
      },
      {
        id: 'size',
        label: '65 ซม.',
      },
    ],
    options: [],
  },
  {
    id: '51908',
    name: 'เตารีดแรงดันไอน้ำ',
    type: 'simple',
    sku: 'CDS12075317',
    urlKey: 'philips-fast-care-steam-generator-gc7703-cds12075317',
    createdAt: '2018-08-14T07:49:55.000Z',
    promotionTag: null,
    collectionName: null,
    priceSummary: {
      original: 11990,
      final: 11990,
      discount: {
        amount: 0,
        percentage: 0,
        effectiveDateRange: null,
      },
    },
    brand: {
      id: '692',
      name: 'PHILIPS',
      urlKey: 'philips',
    },
    mediaGallery: [
      {
        id: '137168',
        title: 'เตารีดแรงดันไอน้ำ',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
        type: 'IMAGE',
        types: ['image', 'small_image', 'thumbnail'],
      },
      {
        id: '137169',
        title: 'เตารีดแรงดันไอน้ำ',
        url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317_x2.jpg',
        type: 'IMAGE',
        types: [],
      },
    ],
    breadcrumbs: [
      {
        id: '5728',
        title: 'home',
        urlKey: 'root/home',
        level: 2,
      },
      {
        id: '5854',
        title: 'laundry_cleaning_storages',
        urlKey: 'root/home/laundry-cleaning-storages',
        level: 3,
      },
      {
        id: '5856',
        title: 'irons_equipments',
        urlKey: 'root/home/laundry-cleaning-storages/irons-equipments',
        level: 4,
      },
      {
        id: '5857',
        title: 'irons',
        urlKey: 'root/home/laundry-cleaning-storages/irons-equipments/irons',
        level: 5,
      },
    ],
    installmentPlans: [],
    the1Redemption: {
      earnPoint: 480,
      redeemPoint: 95920,
    },
    overlayImageUrl: null,
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    preorder: null,
    promotions: [
      {
        id: 'TEST',
        title: 'TEST',
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
      },
    ],
    flashdeal: null,
    reviews: [],
    rating: null,
    shortDescription: '',
    description: '',
    thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
    flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
    purchaseLimit: {
      quantity: {
        min: 1,
        max: 999,
      },
    },
    shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
    paymentMethods: [],
    links: {
      upSellSKUs: [],
      crossSellSKUs: [],
      relatedSKUs: [],
      breadcrumbs: [],
      upSell: [],
      crossSell: [],
      related: [],
      similar: [],
    },
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'เขียว - ชมพู',
      },
      {
        id: 'size',
        label: '65 ซม.',
      },
    ],
    options: [],
  },
];

const mockProductsResultLimit2 = {
  totalCount: 4,
  products: [
    {
      id: '68355',
      name: 'หม้อทอดไฟฟ้า ขนาด 800 กรัม สีดำ',
      type: 'simple',
      sku: 'CDS3551028',
      urlKey: 'philips-avance-collection-airfryer-800-black-cds3551028',
      createdAt: '2018-08-14T08:55:31.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 7990,
        final: 7990,
        discount: {
          amount: 0,
          percentage: 0,
          effectiveDateRange: null,
        },
      },
      brand: {
        id: '692',
        name: 'PHILIPS',
        urlKey: 'philips',
      },
      mediaGallery: [],
      breadcrumbs: [
        {
          id: '5728',
          title: 'home',
          urlKey: 'root/home',
          level: 2,
        },
        {
          id: '5746',
          title: 'cooking_dining',
          urlKey: 'root/home/cooking-dining',
          level: 3,
        },
        {
          id: '5747',
          title: 'cooking_appliances',
          urlKey: 'root/home/cooking-dining/cooking-appliances',
          level: 4,
        },
        {
          id: '5764',
          title: 'fryers',
          urlKey: 'root/home/cooking-dining/cooking-appliances/fryers',
          level: 5,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 320,
        redeemPoint: 63920,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: null,
      flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['STANDARD_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'Fair Ochre',
        },
        {
          id: 'size',
          label: '65 ซม.',
        },
      ],
      options: [],
    },
    {
      id: '51908',
      name: 'เตารีดแรงดันไอน้ำ',
      type: 'simple',
      sku: 'CDS12075317',
      urlKey: 'philips-fast-care-steam-generator-gc7703-cds12075317',
      createdAt: '2018-08-14T07:49:55.000Z',
      promotionTag: null,
      collectionName: null,
      priceSummary: {
        original: 11990,
        final: 11990,
        discount: {
          amount: 0,
          percentage: 0,
          effectiveDateRange: null,
        },
      },
      brand: {
        id: '692',
        name: 'PHILIPS',
        urlKey: 'philips',
      },
      mediaGallery: [
        {
          id: '137168',
          title: 'เตารีดแรงดันไอน้ำ',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
          type: 'IMAGE',
          types: ['image', 'small_image', 'thumbnail'],
        },
        {
          id: '137169',
          title: 'เตารีดแรงดันไอน้ำ',
          url: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317_x2.jpg',
          type: 'IMAGE',
          types: [],
        },
      ],
      breadcrumbs: [
        {
          id: '5728',
          title: 'home',
          urlKey: 'root/home',
          level: 2,
        },
        {
          id: '5854',
          title: 'laundry_cleaning_storages',
          urlKey: 'root/home/laundry-cleaning-storages',
          level: 3,
        },
        {
          id: '5856',
          title: 'irons_equipments',
          urlKey: 'root/home/laundry-cleaning-storages/irons-equipments',
          level: 4,
        },
        {
          id: '5857',
          title: 'irons',
          urlKey: 'root/home/laundry-cleaning-storages/irons-equipments/irons',
          level: 5,
        },
      ],
      installmentPlans: [],
      the1Redemption: {
        earnPoint: 480,
        redeemPoint: 95920,
      },
      overlayImageUrl: null,
      seller: {
        id: 'cds',
        name: 'Central Department Store',
      },
      preorder: null,
      promotions: [
        {
          id: 'TEST',
          title: 'TEST',
          description: 'TEST',
          effectiveDateRange: {
            from: '2018-11-25T17:00:00.000Z',
            to: null,
          },
        },
      ],
      flashdeal: null,
      reviews: [],
      rating: null,
      shortDescription: '',
      description: '',
      thumbnailUrl: 'https://sit-mdc.central.co.th/media/catalog/product/C/D/CDS12075317.jpg',
      flags: ['GIFT_WRAPPING', 'IN_STOCK', 'ONLINE_SALABLE', 'SHOW_PRODUCT_ORIGINAL_PRICE'],
      purchaseLimit: {
        quantity: {
          min: 1,
          max: 999,
        },
      },
      shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
      paymentMethods: [],
      links: {
        upSellSKUs: [],
        crossSellSKUs: [],
        relatedSKUs: [],
        breadcrumbs: [],
        upSell: [],
        crossSell: [],
        related: [],
        similar: [],
      },
      labelOptions: [
        {
          id: 'color_shade_name',
          label: 'เขียว - ชมพู',
        },
        {
          id: 'size',
          label: '65 ซม.',
        },
      ],
      options: [],
    },
  ],
  sorts: [],
  filters: [],
};

const mockDataLakeProductSimilarAndAssociation = {
  id: 1,
  name: 'สินค้าที่คล้ายกัน',
  data: [
    {
      item: ['CDS12635450', 'CDS21103643', 'CDS14353420', 'CDS13830373', 'CDS14353390'],
      code: 'same_brand',
    },
    {
      item: ['CDS14281945', 'CDS12186778', 'CDS12002962', 'CDS23286184'],
      code: 'diff_brand',
    },
  ],
  filler: ['CDS13956882', 'CDS14013386', 'CDS10832400'],
};

export {
  mockProductRecommendedCS,
  mockDataLakeProductRecommendationByUser,
  mockProductsResult,
  mockProductRecommendedCSLimit2,
  mockProductsResultLimit2,
  mockDataLakeProductSimilarAndAssociation,
  mockDataLakeAppProductRecommendationByUser,
};
