const mockFilterRatingOptionsMDC = [
  {
    id: 'norating',
    label: 'Unrated',
    productCount: 1,
  },
  {
    id: '1',
    label: '1',
    productCount: 1,
  },
  {
    id: '2',
    label: '2',
    productCount: 1,
  },
  {
    id: '3',
    label: '3',
    productCount: 1,
  },
  {
    id: '4',
    label: '4',
    productCount: 1,
  },
  {
    id: '5',
    label: '5',
    productCount: 1,
  },
];

const mockFilterRatingOptions = [
  {
    id: 'norating',
    label: 'Unrated',
    productCount: 1,
  },
  {
    id: '1',
    label: '1 Star',
    productCount: 1,
  },
  {
    id: '2',
    label: '2 Stars',
    productCount: 1,
  },
  {
    id: '3',
    label: '3 Stars',
    productCount: 1,
  },
  {
    id: '4',
    label: '4 Stars',
    productCount: 1,
  },
  {
    id: '5',
    label: '5 Stars',
    productCount: 1,
  },
];

const mockFilterAgeRangeOptionsTransform = [
  {
    id: '1',
    label: '3-6',
    productCount: 1,
  },
];

const mockFilterAgeRangeOptionsResult = [
  {
    id: '1',
    label: '3-6',
    productCount: 1,
  },
];

const mockFilterBrandNameOptionsTransform = [
  {
    id: '1',
    label: '360 Fitness',
    productCount: 1,
  },
  {
    id: '2',
    label: 'Acer',
    productCount: 1,
  },
  {
    id: '3',
    label: '@Home',
    productCount: 1,
  },
  {
    id: '4',
    label: 'Écleve',
    productCount: 1,
  },
  {
    id: '5',
    label: 'Zeenzone',
    productCount: 1,
  },
];

const mockFilterBrandNameOptionsResult = [
  {
    id: '2',
    label: 'Acer',
    productCount: 1,
  },
  {
    id: '5',
    label: 'Zeenzone',
    productCount: 1,
  },
  {
    id: '1',
    label: '360 Fitness',
    productCount: 1,
  },
  {
    id: '3',
    label: '@Home',
    productCount: 1,
  },
  {
    id: '4',
    label: 'Écleve',
    productCount: 1,
  },
];

const mockFilterColorOptionsTransform = [
  {
    id: '1',
    label: '#FFFFFF',
    productCount: 1,
  },
  {
    id: '2',
    label: 'น้ำเงิน',
    productCount: 1,
  },
  {
    id: '3',
    label: 'Blue',
    productCount: 1,
  },
  {
    id: '4',
    label: 'แดง',
    productCount: 1,
  },
  {
    id: '5',
    label: '000001',
    productCount: 1,
  },
];

const mockFilterColorOptionsResult = [
  {
    id: '3',
    label: 'Blue',
    productCount: 1,
  },
  {
    id: '2',
    label: 'น้ำเงิน',
    productCount: 1,
  },
  {
    id: '4',
    label: 'แดง',
    productCount: 1,
  },
  {
    id: '5',
    label: '000001',
    productCount: 1,
  },
  {
    id: '1',
    label: '#FFFFFF',
    productCount: 1,
  },
];

const mockDataFindByIdOrSku = {
  suggest_promotions: [
    {
      promotion_name: 'TEST',
      full_condition: 'TEST',
      start_datetime: '2018-11-26',
      end_datetime: 'true',
      label: 'Buy 1000  get free item',
      short_description: 'TEST',
    },
    {
      promotion_name: 'buy more than 2000 discount 50฿',
      full_condition: 'buy more than 1000 discount 50฿',
      start_datetime: '2020-03-24',
      end_datetime: 'true',
      label: 'AUT - buy > = 2000 discount 50฿',
      short_description: 'buy more than 2000 discount 50฿',
    },
  ],
  configurable_products: null,
  shipping_delivery_methods: [
    {
      shipping_method: 'จัดส่งภายในวัน',
      shipping_method_code: 'cds_same_day',
      delivery_method: 'จัดส่งด่วน',
      delivery_method_code: 'delivery',
    },
    {
      shipping_method: 'จัดส่งวันถัดไป',
      shipping_method_code: 'cds_next_day',
      delivery_method: 'จัดส่งด่วน',
      delivery_method_code: 'express_delivery',
    },
  ],
  configurable_product_options: null,
  id: '37397',
  sku: 'CDS16533073',
  name: 'ลิปสติก Rouge G de Guerlain Lipstick Refill สีN°214 ขนาด 3.5 กรัม',
  price: 20,
  breadcrumbs: [
    { category_id: '3060', level: '1', name: 'Beauty', url: 'beauty' },
    {
      category_id: '3092',
      level: '2',
      name: 'เครื่องสำอาง',
      url: 'beauty/makeup',
    },
    {
      category_id: '3111',
      level: '3',
      name: 'ริมฝีปาก',
      url: 'beauty/makeup/lips',
    },
    {
      category_id: '3112',
      level: '4',
      name: 'ลิปสติก',
      url: 'beauty/makeup/lips/lipstick',
    },
  ],
  categories: [
    { name: 'lipstick' },
    { name: 'lips' },
    { name: 'makeup' },
    { name: 'beauty' },
    { name: null },
    { name: null },
    { name: 'ลิปสติก' },
    { name: 'ริมฝีปาก' },
    { name: 'เครื่องสำอาง' },
    { name: 'Beauty' },
  ],
  status: 1,
  visibility: '4',
  type_id: 'simple',
  created_at: '2018-08-14 13:58:25',
  configurable_product_links: null,
  brand_id: '120',
  brand_name: 'GUERLAIN',
  brand_url: 'guerlain',
  color_shade_name: 'N°214',
  color_group_name: ['แดง'],
  image: '/C/D/CDS16533073.jpg',
  url_key: 'guerlain-rouge-g-de-guerlain-lipstick-refill-n0214-3-5-cds16533073',
  special_price: null,
  special_from_date: null,
  special_to_date: null,
  is_in_stock: true,
  new_tag: '1',
  only_at_tag: '0',
  promo_tag: null,
  recommended: '0',
  flash_deal: '0',
  discount_amount: null,
  updated_at: '2020-05-26 09:54:59',
  product_type: 'Normal',
  preorder_shipping_date: null,
  max_sale_qty: 200,
  min_sale_qty: 1,
  collection: null,
  online_exclusive_tag: '1',
  marketplace_product_type_option: null,
  marketplace_seller_option: null,
  flash_deal_enable: null,
  flash_deal_qty: null,
  flash_deal_sold_qty: null,
  flash_deal_from: '2020-03-26 06:10:00',
  flash_deal_to: '2020-07-26 13:10:00',
  is_hide_original_price: null,
  is_show_special_product_name: null,
  news_from_date: null,
  overlay: null,
  ranking: null,
  flash_deal_position: null,
  recommened_sort_order: null,
  manual_boosting: null,
  size: '65 ซม.',
  allow_cc: '1',
  allow_cod: '0',
  allow_express: '0',
  allow_gift_wrapping: '1',
  allow_installment: '0',
  allow_return: '0',
  bu: 'CDS',
  color: null,
  color_shade_id: '6803',
  gift_message_available: 'No',
  gift_wrapping_available: 'No',
  installment_plans: null,
  homepage_new: '0',
  manage_stock: true,
  min_qty: 0,
  payment_methods: null,
  product_id: 37397,
  product_links: null,
  product_sell_type: '445',
  product_status: null,
  shipping_methods: "['จัดส่งภายในวัน', 'จัดส่งวันถัดไป', 'MultiShipping']",
  size_type: true,
  stock_id: 1,
  t1c_earn_points_estimate: [1],
  t1c_redeemable_points: [160],
  thumbnail: '/C/D/CDS16533073.jpg',
  online_salable: true,
  offline_salable: false,
  media_gallery_entries: [
    {
      id: '102080',
      types: [[]],
      file: '/C/D/CDS16533073.jpg',
      media_type: 'image',
      label: true,
      position: '1',
      disabled: false,
    },
    {
      id: '102081',
      types: [],
      file: '/C/D/CDS16533073_x2.jpg',
      media_type: 'image',
      label: true,
      position: '2',
      disabled: false,
    },
  ],
  media_gallery_entries_video: [
    {
      id: '1269553',
      store_id: 'en',
      provider: '',
      url: 'https://www.youtube.com/watch?v=7NW1BxPuwAk',
      title: 'Roomba i7+ Review - 6 Months Later',
      description: 'A long term review of the iRobot...',
      metadata: '',
    },
  ],
  marketplace: null,
  overall_rating: {
    rating_id: true,
    rating: 5,
    category: 'true',
    option_id: true,
    total_vote: 1,
    five_star: 1,
    four_star: 0,
    three_star: 0,
    two_star: 0,
    one_star: 0,
    rounded_rating: 5,
  },
  brand: {
    brand_id: 120,
    name: 'GUERLAIN',
    website_ids: [1],
    url_key: 'guerlain',
    logo: null,
    is_featured: false,
    extension_attributes: {
      menu_css: null,
      parent_category: null,
      position: 0,
      product_count: 255,
      product_name_special: null,
      hide_product_original_price: null,
      hide_t1c_redeemable_amount: null,
      allow_product_review: null,
    },
  },
};

const mockProductDetailCSResponse = {
  id: '177748',
  sku: 'GRCDS18090002',
  description: 'description',
  created_at: '2018-08-14 15:21:50',
  type_id: 'configurable',
  configurable_product_options: [
    {
      id: 369,
      attribute_id: '184',
      label: 'Size',
      values: [
        {
          value_index: 2920,
          extension_attributes: {
            label: '15 mL',
            products: ['78737'],
            frontend_type: 'swatch_text',
            frontend_value: '15 mL',
          },
        },
        {
          value_index: 2937,
          extension_attributes: {
            label: '50 mL',
            products: ['60033'],
            frontend_type: 'swatch_text',
            frontend_value: '50 mL',
          },
        },
        {
          value_index: 2956,
          extension_attributes: {
            label: '97 mL',
            products: ['52191'],
            frontend_type: 'swatch_text',
            frontend_value: '97 mL',
          },
        },
      ],
    },
  ],
  configurable_products: [
    {
      id: '60033',
      sku: 'CDS12063154',
      name: 'Age Rescue Water-Charged Gel Cream 50 mL',
      description: 'description',
      created_at: '2018-08-14 15:21:50',
    },
  ],
};

const mockProductDetailResponse = [
  {
    id: '177748',
    sku: 'GRCDS18090002',
    description: 'description',
    type: 'configurable',
    children: [
      {
        options: [
          {
            id: '184',
            label: 'Size',
          },
        ],
        product: {
          id: '60033',
          sku: 'CDS12063154',
          name: 'Age Rescue Water-Charged Gel Cream 50 mL',
          description: 'description',
        },
      },
    ],
  },
  {
    id: '123123',
    sku: 'CDS20283674',
    description: 'description',
  },
];

const mockProductDetailResponse2 = [
  {
    id: '177748',
    sku: 'GRCDS18090002',
    description: 'description',
    type: 'configurable',
    children: [
      {
        options: [
          {
            id: '184',
            label: 'Size',
          },
        ],
        product: {
          id: '60033',
          sku: 'CDS12063154',
          name: 'Age Rescue Water-Charged Gel Cream 50 mL',
          description: 'description',
        },
      },
    ],
  },
  {
    id: '123123',
    sku: 'CDS20283674',
    description: 'description',
  },
  {
    id: '312312',
    sku: 'CDS15724151',
    description: 'description',
  },
];

const mockProductDetailResult = {
  id: '177748',
  sku: 'GRCDS18090002',
  description: 'description',
  type: 'configurable',
  children: [
    {
      options: [
        {
          id: '184',
          label: 'Size',
        },
      ],
      product: {
        id: '60033',
        sku: 'CDS12063154',
        name: 'Age Rescue Water-Charged Gel Cream 50 mL',
        description: 'description',
      },
    },
  ],
};

export const mockCartPriceRuleOverlays = [
  {
    rule_id: '983',
    product_id: '44051',
    overlay_image: 'salesrule_overlay/11111.png',
    display_priority: '1',
  },
  {
    rule_id: '983',
    product_id: '44051',
    overlay_image: 'salesrule_overlay/22222.png',
    display_priority: '2',
  },
];

const mockProductData = {
  id: 416505,
  name: 'เครื่องปั่นร้อนเย็นพลังสูง Hot & Cold High Speed Blender (2.7ลิตร, 1300วัตต์) รุ่น BL985A66 ',
  sku: 'CDS19287492',
  custom_attributes_option: [
    {
      attribute_code: '1',
      value: '1',
    },
  ],
  breadcrumbs: [],
  attribute_set_id: 1,
  price: 1,
  status: 1,
  visibility: 4,
  type_id: 'simple',
  created_at: '2020-12-18 00:00:00',
  updated_at: '2020-12-18 00:01:00',
  extension_attributes: {
    website_ids: [],
    category_links: [],
    stock_item: {
      item_id: 1,
      product_id: 1,
      stock_id: 1,
      qty: 1,
      is_in_stock: false,
      is_qty_decimal: false,
      show_default_notification_message: false,
      use_config_min_qty: false,
      min_qty: 1,
      use_config_min_sale_qty: 1,
      min_sale_qty: 1,
      use_config_max_sale_qty: false,
      max_sale_qty: 1,
      use_config_backorders: false,
      backorders: 1,
      use_config_notify_stock_qty: false,
      notify_stock_qty: 1,
      use_config_qty_increments: false,
      qty_increments: 1,
      use_config_enable_qty_inc: false,
      enable_qty_increments: false,
      use_config_manage_stock: false,
      manage_stock: false,
      low_stock_date: '2020-12-18 00:02:00',
      is_decimal_divided: false,
      stock_status_changed_auto: 1,
    },
    installment_plans: [],
    overall_rating: {
      rating_id: '',
      rating: '',
      category: '',
      option_id: '',
      total_vote: 1,
      five_star: 1,
      four_star: 1,
      three_star: 1,
      two_star: 1,
      one_star: 1,
    },
    reviews: [],
    specification_attributes: [],
    brand: {
      brand_id: 1,
      attribute_id: 1,
      attribute_code: '1',
      option_id: 1,
      name: '1',
      website_ids: [],
      url_key: '1',
      is_featured: false,
      content: [],
      meta_title: '1',
      meta_description: '1',
      description: '1',
      brand_additional_products: [],
      extension_attributes: {
        parent_category: 1,
        position: 1,
        is_official: false,
        product_collections: [],
        product_count: 1,
        product_name_special: false,
        hide_product_original_price: false,
        hide_t1c_redeemable_amount: false,
        allow_product_review: false,
        banners: [],
      },
    },
    size_map: [],
    size_maps: [],
    category_paths: [],
    t1c_redeemable_points: [],
    t1c_earn_points_estimate: [],
    overlay_image: '1',
    overlay_status: '1',
    overlay_mobile_status: '1',
    overlay_start_date: '2020-12-18 00:03:00',
    overlay_end_date: '2020-12-18 00:04:00',
    configurable_product_options: [],
    configurable_product_links: [],
    suggest_promotions: [],
  },
  product_links: [],
  options: [],
  media_gallery_entries: [
    {
      id: 102080,
      types: [],
      file: '/C/D/CDS16533073.jpg',
      media_type: 'image',
      label: true,
      position: 1,
      disabled: false,
      extension_attributes: {
        video_content: {
          media_type: '1',
          video_provider: '1',
          video_url: '1',
          video_title: '1',
          video_description: '1',
          video_metadata: '1',
        },
      },
    },
  ],
  tier_prices: [],
  custom_attributes: [
    {
      attribute_code: 'url_key',
      value: '1',
      label: '1',
      name: '1',
    },
  ],
};

const mockStoreConfig = {
  id: 1,
  code: '1',
  website_id: 1,
  locale: '1',
  base_currency_code: '1',
  default_display_currency_code: '1',
  timezone: '1',
  weight_unit: '1',
  base_url: '1',
  base_link_url: '1',
  base_static_url: '1',
  base_media_url: '1',
  secure_base_url: '1',
  secure_base_link_url: '1',
  secure_base_static_url: '1',
  secure_base_media_url: '1',
  extension_attributes: {
    social_facebook_app_id: '1',
    social_facebook_app_secret: '1',
    grab_url: '1',
    grab_client_id: '1',
  },
};

const mockSuggestPromotion = {
  rule_id: 1,
  rule_is_active: false,
  rule_sort_order: 1,
  rule_name: '1',
  action_type: '1',
  label: '1',
  coupon_code: '1',
  start_datetime: '1',
  end_datetime: '1',
  promotion_name: '1',
  full_condition: '1',
  short_description: '1',
  display_priority: 1,
};

export const mockCatalogServiceSearchResponse = {
  total: 4,
  products: [
    {
      suggest_promotions: [
        {
          promotion_name: 'TEST',
          full_condition: 'TEST',
          start_datetime: '2018-11-26',
          end_datetime: 'true',
          label: 'Buy 1000  get free item',
          short_description: 'TEST',
        },
      ],
      configurable_products: [
        {
          suggest_promotions: [
            {
              promotion_name: 'TEST',
              full_condition: 'TEST',
              start_datetime: '2018-11-26',
              end_datetime: 'true',
              label: 'Buy 1000  get free item',
              short_description: 'TEST',
            },
          ],
          shipping_delivery_methods: [
            {
              shipping_method: 'จัดส่งภายในวัน',
              shipping_method_code: 'cds_same_day',
              delivery_method: 'จัดส่งด่วน',
              delivery_method_code: 'express_delivery',
            },
            {
              shipping_method: 'จัดส่งวันถัดไป',
              shipping_method_code: 'cds_next_day',
              delivery_method: 'จัดส่งด่วน',
              delivery_method_code: 'express_delivery',
            },
          ],
          id: '23281',
          sku: 'CDS15724144',
          name: '[Size TH 75 cm, 02] แท่นชาร์จไร้สาย Power Cube X สีขาว',
          price: 20,
          breadcrumbs: [
            {
              category_id: '5928',
              level: '2',
              name: 'gadgets_tech',
              url: 'root/gadgets-tech',
            },
            {
              category_id: '5937',
              level: '3',
              name: 'mobiles_tablets',
              url: 'root/gadgets-tech/mobiles-tablets',
            },
            {
              category_id: '5938',
              level: '4',
              name: 'mobile_phones',
              url: 'root/gadgets-tech/mobiles-tablets/mobile-phones',
            },
          ],
          categories: [
            { name: 'mobile_phones' },
            { name: 'mobiles_tablets' },
            { name: 'gadgets_tech' },
            { name: null },
            { name: null },
            { name: 'มือถือ' },
            { name: null },
            { name: 'เทคโนโลยี' },
            { name: 'tablets' },
            { name: 'แท็บเล็ต' },
            { name: 'mobile_tablet_accessories' },
            { name: 'อุปกรณ์เสริมมือถือและแท็บเล็ต' },
          ],
          status: 1,
          visibility: '4',
          type_id: 'simple',
          created_at: '2018-08-14 12:37:02',
          brand_id: '10068',
          brand_name: 'MIPOW',
          brand_url: 'mipow',
          color_shade_name: '02',
          color_group_name: ['เขียวเข้ม'],
          image: '/C/D/CDS15724144.jpg',
          url_key: 'mipow-combo-wireless-charger-power-cube-x-white-cds15724144',
          special_price: null,
          special_from_date: null,
          special_to_date: null,
          is_in_stock: true,
          new_tag: null,
          only_at_tag: '0',
          promo_tag: null,
          recommended: null,
          flash_deal: null,
          discount_amount: null,
          updated_at: '2019-12-17 17:00:20',
          product_type: 'Normal',
          preorder_shipping_date: null,
          max_sale_qty: 200,
          min_sale_qty: 1,
          collection: null,
          online_exclusive_tag: '0',
          marketplace_product_type_option: null,
          marketplace_seller_option: null,
          flash_deal_enable: null,
          flash_deal_qty: null,
          flash_deal_sold_qty: null,
          flash_deal_from: null,
          flash_deal_to: null,
          is_hide_original_price: null,
          is_show_special_product_name: null,
          news_from_date: null,
          overlay: null,
          ranking: null,
          flash_deal_position: null,
          recommened_sort_order: null,
          manual_boosting: null,
          size: '75 cm',
          allow_cc: '1',
          allow_cod: null,
          allow_express: '0',
          allow_gift_wrapping: '1',
          allow_installment: '0',
          allow_return: '0',
          bu: 'CDS',
          color: null,
          color_shade_id: '27180',
          gift_message_available: null,
          gift_wrapping_available: null,
          installment_plans: null,
          homepage_new: null,
          manage_stock: true,
          min_qty: 0,
          payment_methods: null,
          product_id: 7507,
          product_links: null,
          product_sell_type: '445',
          product_status: null,
          shipping_methods: "['จัดส่งภายในวัน', 'จัดส่งวันถัดไป', 'MultiShipping']",
          size_type: null,
          stock_id: 1,
          t1c_earn_points_estimate: [1],
          t1c_redeemable_points: [160],
          thumbnail: '/C/D/CDS15724144.jpg',
          online_salable: true,
          offline_salable: false,
          media_gallery_entries: [
            {
              id: '14820',
              types: ['image', 'small_image', 'thumbnail'],
              file: '/C/D/CDS15724144.jpg',
              media_type: 'image',
              label: true,
              position: '1',
              disabled: false,
            },
          ],
          marketplace: null,
          overall_rating: {
            rating_id: true,
            rating: 0,
            category: 'true',
            option_id: true,
            total_vote: 0,
            five_star: 0,
            four_star: 0,
            three_star: 0,
            two_star: 0,
            one_star: 0,
            rounded_rating: null,
          },
          brand: {
            brand_id: 1437,
            name: 'MIPOW',
            website_ids: [1],
            url_key: 'mipow',
            logo: null,
            is_featured: false,
            extension_attributes: {
              menu_css: null,
              parent_category: null,
              position: 0,
              product_count: 0,
              product_name_special: null,
              hide_product_original_price: null,
              hide_t1c_redeemable_amount: null,
              allow_product_review: null,
            },
          },
        },
      ],
      shipping_delivery_methods: [
        {
          shipping_method: 'จัดส่งภายในวัน',
          shipping_method_code: 'cds_same_day',
          delivery_method: 'จัดส่งด่วน',
          delivery_method_code: 'express_delivery',
        },
        {
          shipping_method: 'จัดส่งวันถัดไป',
          shipping_method_code: 'cds_next_day',
          delivery_method: 'จัดส่งด่วน',
          delivery_method_code: 'express_delivery',
        },
      ],
      configurable_product_options: [
        {
          id: 66316,
          attribute_id: '410',
          label: 'Shade',
          values: [
            {
              value_index: 29892,
              extension_attributes: {
                label: 'Deep Throat',
                products: ['23281'],
                frontend_type: 'swatch_color',
                frontend_value: '#f07aa2',
              },
            },
            {
              value_index: 30696,
              extension_attributes: {
                label: ' Gina',
                products: ['23282'],
                frontend_type: 'swatch_color',
                frontend_value: '#f07448',
              },
            },
          ],
        },
      ],
      id: '7507',
      sku: 'CDS15724144',
      name: '[Size TH 75 cm, 02] แท่นชาร์จไร้สาย Power Cube X สีขาว',
      price: 20,
      breadcrumbs: [
        {
          category_id: '5928',
          level: '2',
          name: 'gadgets_tech',
          url: 'root/gadgets-tech',
        },
        {
          category_id: '5937',
          level: '3',
          name: 'mobiles_tablets',
          url: 'root/gadgets-tech/mobiles-tablets',
        },
        {
          category_id: '5938',
          level: '4',
          name: 'mobile_phones',
          url: 'root/gadgets-tech/mobiles-tablets/mobile-phones',
        },
      ],
      categories: [
        { name: 'mobile_phones' },
        { name: 'mobiles_tablets' },
        { name: 'gadgets_tech' },
        { name: null },
        { name: null },
        { name: 'มือถือ' },
        { name: null },
        { name: 'เทคโนโลยี' },
        { name: 'tablets' },
        { name: 'แท็บเล็ต' },
        { name: 'mobile_tablet_accessories' },
        { name: 'อุปกรณ์เสริมมือถือและแท็บเล็ต' },
      ],
      status: 1,
      visibility: '4',
      type_id: 'configurable',
      created_at: '2018-08-14 12:37:02',
      configurable_product_links: null,
      brand_id: '10068',
      brand_name: 'MIPOW',
      brand_url: 'mipow',
      color_shade_name: '02',
      color_group_name: ['เขียวเข้ม'],
      image: '/C/D/CDS15724144.jpg',
      url_key: 'mipow-combo-wireless-charger-power-cube-x-white-cds15724144',
      special_price: null,
      special_from_date: null,
      special_to_date: null,
      is_in_stock: true,
      new_tag: null,
      only_at_tag: '0',
      promo_tag: null,
      recommended: null,
      flash_deal: null,
      discount_amount: null,
      updated_at: '2019-12-17 17:00:20',
      product_type: 'Normal',
      preorder_shipping_date: null,
      max_sale_qty: 200,
      min_sale_qty: 1,
      collection: null,
      online_exclusive_tag: '0',
      marketplace_product_type_option: null,
      marketplace_seller_option: null,
      flash_deal_enable: null,
      flash_deal_qty: null,
      flash_deal_sold_qty: null,
      flash_deal_from: null,
      flash_deal_to: null,
      is_hide_original_price: null,
      is_show_special_product_name: null,
      news_from_date: null,
      overlay: null,
      ranking: null,
      flash_deal_position: null,
      recommened_sort_order: null,
      manual_boosting: null,
      size: '75 cm',
      allow_cc: '1',
      allow_cod: null,
      allow_express: '0',
      allow_gift_wrapping: '1',
      allow_installment: '0',
      allow_return: '0',
      bu: 'CDS',
      color: null,
      color_shade_id: '27180',
      gift_message_available: null,
      gift_wrapping_available: null,
      installment_plans: null,
      homepage_new: null,
      manage_stock: true,
      min_qty: 0,
      payment_methods: null,
      product_id: 7507,
      product_links: null,
      product_sell_type: '445',
      product_status: null,
      shipping_methods: "['จัดส่งภายในวัน', 'จัดส่งวันถัดไป', 'MultiShipping']",
      size_type: null,
      stock_id: 1,
      t1c_earn_points_estimate: [1],
      t1c_redeemable_points: [160],
      thumbnail: '/C/D/CDS15724144.jpg',
      online_salable: true,
      offline_salable: false,
      media_gallery_entries: [
        {
          id: '14820',
          types: ['image', 'small_image', 'thumbnail'],
          file: '/C/D/CDS15724144.jpg',
          media_type: 'image',
          label: true,
          position: '1',
          disabled: false,
        },
      ],
      marketplace: null,
      overall_rating: {
        rating_id: true,
        rating: 0,
        category: 'true',
        option_id: true,
        total_vote: 0,
        five_star: 0,
        four_star: 0,
        three_star: 0,
        two_star: 0,
        one_star: 0,
        rounded_rating: null,
      },
      brand: {
        brand_id: 1437,
        name: 'MIPOW',
        website_ids: [1],
        url_key: 'mipow',
        logo: null,
        is_featured: false,
        extension_attributes: {
          menu_css: null,
          parent_category: null,
          position: 0,
          product_count: 0,
          product_name_special: null,
          hide_product_original_price: null,
          hide_t1c_redeemable_amount: null,
          allow_product_review: null,
        },
      },
    },
  ],
  aggregations: [
    {
      label: null,
      field: 'shoe_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'bottle_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'shipping_delivery_methods.delivery_method',
      value: null,
      position: null,
      buckets: [
        { key: 'จัดส่งด่วน', doc_count: 4 },
        { key: 'จัดส่งปกติ', doc_count: 1 },
        { key: 'รับเวลาปกติ', doc_count: 1 },
        { key: 'รับใน 1 ชั่วโมง', doc_count: 1 },
        { key: 'ส่งด่วนใน 3 ชั่วโมง', doc_count: 1 },
      ],
    },
    {
      label: null,
      field: 'material_general',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'battery_time',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'rating',
      value: null,
      position: null,
      buckets: [
        { key: 'norating', doc_count: 3 },
        { key: '1', doc_count: 0 },
        { key: '2', doc_count: 0 },
        { key: '3', doc_count: 0 },
        { key: '4', doc_count: 1 },
        { key: '5', doc_count: 0 },
      ],
    },
    {
      label: null,
      field: 'milk_powder_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_shoes_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'diaper_weight',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'clothing_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_underwear_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'age_range',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'cordless',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'categories.id',
      value: null,
      position: 0,
      buckets: [
        { key: '260', doc_count: 4 },
        { key: '5451', doc_count: 4 },
        { key: '3061', doc_count: 3 },
        { key: '3984', doc_count: 3 },
        { key: '3985', doc_count: 3 },
        { key: '3986', doc_count: 3 },
        { key: '3987', doc_count: 3 },
        { key: '5928', doc_count: 3 },
        { key: '5937', doc_count: 3 },
        { key: '5938', doc_count: 3 },
        { key: '5939', doc_count: 3 },
        { key: '5940', doc_count: 3 },
        { key: '3055', doc_count: 1 },
        { key: '3879', doc_count: 1 },
        { key: '3900', doc_count: 1 },
        { key: '3902', doc_count: 1 },
        { key: '3976', doc_count: 1 },
        { key: '3979', doc_count: 1 },
        { key: '3982', doc_count: 1 },
        { key: '3983', doc_count: 1 },
        { key: '3988', doc_count: 1 },
        { key: '3993', doc_count: 1 },
        { key: '4000', doc_count: 1 },
        { key: '4016', doc_count: 1 },
        { key: '5728', doc_count: 1 },
        { key: '5883', doc_count: 1 },
        { key: '5904', doc_count: 1 },
        { key: '5906', doc_count: 1 },
      ],
    },
    {
      label: null,
      field: '3hr_th_configurable_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'coffee_maker_technology',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'battery_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'pm2_5',
      value: null,
      position: null,
      buckets: [{ key: '0', doc_count: 1 }],
    },
    {
      label: null,
      field: 'shoe_material',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'digital_manual',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'microphone',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'necklace_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'luggage_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'accessory_jewelry_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'brand_name',
      value: null,
      position: 1,
      buckets: [
        { key: 'mipow', doc_count: 3 },
        { key: 'my carr', doc_count: 1 },
      ],
    },
    {
      label: null,
      field: 'boil_function',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'capacity_grams',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'home_clock_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_occasion',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'inverter_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'filtration',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'pm25',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: '1hr_th_simple_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'ro',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'room_size_sqm',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'gender',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'weight_kg',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'pattern',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'racket',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'app_connected',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_neckline',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'bracelet_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'capacity_lts',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'life_luggage_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'material_clothing',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'milk_powder_formula',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'car_seat_age',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: '3hr_en_configurable_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: '3hr_th_simple_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'pacifier_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'waterproof',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_swimwear_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: '3hr_en_simple_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'grill_mode',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'kid_diaper_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'btu',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'filtrations',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'sets',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'density',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_sleeves_level',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'inverter',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'diaper_size',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_pant_fit',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'style_general',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_heel_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: '1hr_en_simple_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'material_dial',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'color_group_name',
      value: null,
      position: 2,
      buckets: [
        { key: 'เขียวเข้ม', doc_count: 2 },
        { key: 'ดำ', doc_count: 1 },
      ],
    },
    {
      label: null,
      field: 'anti_calc_clean',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: '1hr_th_configurable_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: '1hr_en_configurable_total',
      value: null,
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'dress_length',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'fashion_socks_type',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'descaling_system',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'wireless',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'watt',
      value: null,
      position: null,
      buckets: [],
    },
    {
      label: null,
      field: 'min_price',
      value: '20.0',
      position: null,
      buckets: null,
    },
    {
      label: null,
      field: 'max_price',
      value: '2450.0',
      position: null,
      buckets: null,
    },
  ],
  category_aggregations: [
    {
      id: '3061',
      name: 'เทคโนโลยี',
      parent_id: '260',
      level: '2',
      url_path: 'tech',
      doc_count: 3,
      url_key: 'tech',
    },
    {
      id: '3985',
      name: 'มือถือ',
      parent_id: '3984',
      level: '4',
      url_path: 'tech/mobiles-tablets/mobile-phones',
      doc_count: 3,
      url_key: 'mobile-phones',
    },
    {
      id: '3986',
      name: 'แท็บเล็ต',
      parent_id: '3984',
      level: '4',
      url_path: 'tech/mobiles-tablets/tablets',
      doc_count: 3,
      url_key: 'tablets',
    },
    {
      id: '3987',
      name: 'อุปกรณ์เสริมมือถือและแท็บเล็ต',
      parent_id: '3984',
      level: '4',
      url_path: 'tech/mobiles-tablets/mobile-tablet-accessories',
      doc_count: 3,
      url_key: 'mobile-tablet-accessories',
    },
    {
      id: '5928',
      name: 'gadgets_tech',
      parent_id: '5451',
      level: '3',
      url_path: 'root/gadgets-tech',
      doc_count: 3,
      url_key: 'gadgets-tech',
    },
    {
      id: '5937',
      name: 'mobiles_tablets',
      parent_id: '5928',
      level: '4',
      url_path: 'root/gadgets-tech/mobiles-tablets',
      doc_count: 3,
      url_key: 'mobiles-tablets',
    },
    {
      id: '5938',
      name: 'mobile_phones',
      parent_id: '5937',
      level: '5',
      url_path: 'root/gadgets-tech/mobiles-tablets/mobile-phones',
      doc_count: 3,
      url_key: 'mobile-phones',
    },
    {
      id: '5939',
      name: 'tablets',
      parent_id: '5937',
      level: '5',
      url_path: 'root/gadgets-tech/mobiles-tablets/tablets',
      doc_count: 3,
      url_key: 'tablets',
    },
    {
      id: '5940',
      name: 'mobile_tablet_accessories',
      parent_id: '5937',
      level: '5',
      url_path: 'root/gadgets-tech/mobiles-tablets/mobile-tablet-accessories',
      doc_count: 3,
      url_key: 'mobile-tablet-accessories',
    },
    {
      id: '3055',
      name: 'บ้าน',
      parent_id: '260',
      level: '2',
      url_path: 'home',
      doc_count: 1,
      url_key: 'home',
    },
    {
      id: '3879',
      name: 'Outdoor - Tools - Automotive',
      parent_id: '3055',
      level: '3',
      url_path: 'home/outdoor-tools-automotive',
      doc_count: 1,
      url_key: 'outdoor-tools-automotive',
    },
    {
      id: '3902',
      name: 'ผลิตภัณฑ์ทำความสะอาดและเคลือบเงา',
      parent_id: '3900',
      level: '5',
      url_path: 'home/outdoor-tools-automotive/car-care/wash-shampoo-coating',
      doc_count: 1,
      url_key: 'wash-shampoo-coating',
    },
    {
      id: '3976',
      name: 'แก็ดเจ็ตสำหรับสวมใส่',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/wearable-gadgets',
      doc_count: 1,
      url_key: 'wearable-gadgets',
    },
    {
      id: '3979',
      name: 'Audio & Hi-Fi',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/audio-hifi',
      doc_count: 1,
      url_key: 'audio-hifi',
    },
    {
      id: '3983',
      name: 'โดรน',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/drones',
      doc_count: 1,
      url_key: 'drones',
    },
    {
      id: '3988',
      name: 'Computers',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/computers',
      doc_count: 1,
      url_key: 'computers',
    },
    {
      id: '3993',
      name: 'Cameras',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/cameras',
      doc_count: 1,
      url_key: 'cameras',
    },
    {
      id: '4000',
      name: 'เครื่องใช้ไฟฟ้าในบ้าน',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/home-appliances',
      doc_count: 1,
      url_key: 'home-appliances',
    },
    {
      id: '4016',
      name: 'เครื่องใช้ไฟฟ้าในครัว',
      parent_id: '3061',
      level: '3',
      url_path: 'tech/cooking-appliances',
      doc_count: 1,
      url_key: 'cooking-appliances',
    },
    {
      id: '5728',
      name: 'home',
      parent_id: '5451',
      level: '3',
      url_path: 'root/home',
      doc_count: 1,
      url_key: 'home',
    },
    {
      id: '5883',
      name: 'outdoor_tools_automotive',
      parent_id: '5728',
      level: '4',
      url_path: 'root/home/outdoor-tools-automotive',
      doc_count: 1,
      url_key: 'outdoor-tools-automotive',
    },
    {
      id: '5904',
      name: 'car_care',
      parent_id: '5883',
      level: '5',
      url_path: 'root/home/outdoor-tools-automotive/car-care',
      doc_count: 1,
      url_key: 'car-care',
    },
    {
      id: '5906',
      name: 'wash_shampoo_coating',
      parent_id: '5904',
      level: '6',
      url_path: 'root/home/outdoor-tools-automotive/car-care/wash-shampoo-coating',
      doc_count: 1,
      url_key: 'wash-shampoo-coating',
    },
  ],
};

const mockDataFindBySKUsNew = [
  {
    suggest_promotions: [
      {
        promotion_name: 'TEST',
        full_condition: 'TEST',
        start_datetime: '2018-11-26',
        end_datetime: 'true',
        label: 'Buy 1000  get free item',
        short_description: 'TEST',
      },
      {
        promotion_name: 'buy more than 2000 discount 50฿',
        full_condition: 'buy more than 1000 discount 50฿',
        start_datetime: '2020-03-24',
        end_datetime: 'true',
        label: 'AUT - buy > = 2000 discount 50฿',
        short_description: 'buy more than 2000 discount 50฿',
      },
    ],
    configurable_products: null,
    shipping_delivery_methods: [
      {
        shipping_method: 'จัดส่งภายในวัน',
        shipping_method_code: 'cds_same_day',
        delivery_method: 'จัดส่งด่วน',
        delivery_method_code: 'delivery',
      },
      {
        shipping_method: 'จัดส่งวันถัดไป',
        shipping_method_code: 'cds_next_day',
        delivery_method: 'จัดส่งด่วน',
        delivery_method_code: 'express_delivery',
      },
    ],
    configurable_product_options: null,
    id: '37397',
    sku: 'CDS16533073',
    name: 'ลิปสติก Rouge G de Guerlain Lipstick Refill สีN°214 ขนาด 3.5 กรัม',
    price: 20,
    breadcrumbs: [
      { category_id: '3060', level: '1', name: 'Beauty', url: 'beauty' },
      {
        category_id: '3092',
        level: '2',
        name: 'เครื่องสำอาง',
        url: 'beauty/makeup',
      },
      {
        category_id: '3111',
        level: '3',
        name: 'ริมฝีปาก',
        url: 'beauty/makeup/lips',
      },
      {
        category_id: '3112',
        level: '4',
        name: 'ลิปสติก',
        url: 'beauty/makeup/lips/lipstick',
      },
    ],
    categories: [
      { id: '1', name: 'lipstick' },
      { id: '2', name: 'lips' },
      { id: '3', name: 'makeup' },
      { id: '4', name: 'beauty' },
      { id: '5', name: null },
      { id: '6', name: null },
      { id: '7', name: 'ลิปสติก' },
      { id: '8', name: 'ริมฝีปาก' },
      { id: '9', name: 'เครื่องสำอาง' },
      { id: '10', name: 'Beauty' },
    ],
    status: 1,
    visibility: '4',
    type_id: 'simple',
    created_at: '2018-08-14 13:58:25',
    configurable_product_links: null,
    brand_id: '120',
    brand_name: 'GUERLAIN',
    brand_url: 'guerlain',
    color_shade_name: 'N°214',
    color_group_name: ['แดง'],
    image: '/C/D/CDS16533073.jpg',
    url_key: 'guerlain-rouge-g-de-guerlain-lipstick-refill-n0214-3-5-cds16533073',
    special_price: null,
    special_from_date: null,
    special_to_date: null,
    is_in_stock: true,
    new_tag: '1',
    only_at_tag: '0',
    promo_tag: null,
    recommended: '0',
    flash_deal: '0',
    discount_amount: null,
    updated_at: '2020-05-26 09:54:59',
    product_type: 'Normal',
    preorder_shipping_date: null,
    max_sale_qty: 200,
    min_sale_qty: 1,
    collection: null,
    online_exclusive_tag: '1',
    marketplace_product_type_option: null,
    marketplace_seller_option: null,
    flash_deal_enable: null,
    flash_deal_qty: null,
    flash_deal_sold_qty: null,
    flash_deal_from: '2020-03-26 06:10:00',
    flash_deal_to: '2020-07-26 13:10:00',
    is_hide_original_price: null,
    is_show_special_product_name: null,
    news_from_date: null,
    overlay: null,
    ranking: null,
    flash_deal_position: null,
    recommened_sort_order: null,
    manual_boosting: null,
    size: '65 ซม.',
    allow_cc: '1',
    allow_cod: '0',
    allow_express: '0',
    allow_gift_wrapping: '1',
    allow_installment: '0',
    allow_return: '0',
    bu: 'CDS',
    color: null,
    color_shade_id: '6803',
    gift_message_available: 'No',
    gift_wrapping_available: 'No',
    installment_plans: null,
    homepage_new: '0',
    manage_stock: true,
    min_qty: 0,
    payment_methods: null,
    product_id: 37397,
    product_links: null,
    product_sell_type: '445',
    product_status: null,
    shipping_methods: "['จัดส่งภายในวัน', 'จัดส่งวันถัดไป', 'MultiShipping']",
    size_type: true,
    stock_id: 1,
    t1c_earn_points_estimate: [1],
    t1c_redeemable_points: [160],
    thumbnail: '/C/D/CDS16533073.jpg',
    online_salable: true,
    offline_salable: false,
    media_gallery_entries: [
      {
        id: '102080',
        types: [[]],
        file: '/C/D/CDS16533073.jpg',
        media_type: 'image',
        label: true,
        position: '1',
        disabled: false,
      },
      {
        id: '102081',
        types: [],
        file: '/C/D/CDS16533073_x2.jpg',
        media_type: 'image',
        label: true,
        position: '2',
        disabled: false,
      },
    ],
    media_gallery_entries_video: [
      {
        id: '1269553',
        store_id: 'en',
        provider: '',
        url: 'https://www.youtube.com/watch?v=7NW1BxPuwAk',
        title: 'Roomba i7+ Review - 6 Months Later',
        description: 'A long term review of the iRobot...',
        metadata: '',
      },
    ],
    marketplace: null,
    overall_rating: {
      rating_id: true,
      rating: 5,
      category: 'true',
      option_id: true,
      total_vote: 1,
      five_star: 1,
      four_star: 0,
      three_star: 0,
      two_star: 0,
      one_star: 0,
      rounded_rating: 5,
    },
    brand: {
      brand_id: 120,
      name: 'GUERLAIN',
      website_ids: [1],
      url_key: 'guerlain',
      logo: null,
      is_featured: false,
      extension_attributes: {
        menu_css: null,
        parent_category: null,
        position: 0,
        product_count: 255,
        product_name_special: null,
        hide_product_original_price: null,
        hide_t1c_redeemable_amount: null,
        allow_product_review: null,
      },
    },
  },
];

const mockResponseFindBySKUsNew = [
  {
    brand: {
      id: '120',
      name: 'GUERLAIN',
      urlKey: 'guerlain',
    },
    breadcrumbs: [
      {
        id: '3060',
        level: 1,
        title: 'Beauty',
        urlKey: 'beauty',
      },
      {
        id: '3092',
        level: 2,
        title: 'เครื่องสำอาง',
        urlKey: 'beauty/makeup',
      },
      {
        id: '3111',
        level: 3,
        title: 'ริมฝีปาก',
        urlKey: 'beauty/makeup/lips',
      },
      {
        id: '3112',
        level: 4,
        title: 'ลิปสติก',
        urlKey: 'beauty/makeup/lips/lipstick',
      },
    ],
    categories: [
      { id: '1', name: 'lipstick' },
      { id: '2', name: 'lips' },
      { id: '3', name: 'makeup' },
      { id: '4', name: 'beauty' },
      { id: '5', name: '' },
      { id: '6', name: '' },
      { id: '7', name: 'ลิปสติก' },
      { id: '8', name: 'ริมฝีปาก' },
      { id: '9', name: 'เครื่องสำอาง' },
      { id: '10', name: 'Beauty' },
    ],
    collectionName: null,
    createdAt: '2018-08-14T06:58:25.000Z',
    description: '',
    flags: [
      'NEW',
      'ONLINE_EXCLUSIVE',
      'GIFT_WRAPPING',
      'IN_STOCK',
      'BEAUTY',
      'ONLINE_SALABLE',
      'SHOW_PRODUCT_ORIGINAL_PRICE',
    ],
    flashdeal: null,
    id: '37397',
    installmentPlans: [],
    labelOptions: [
      {
        id: 'color_shade_name',
        label: 'N°214',
      },
      {
        id: 'size',
        label: '65 ซม.',
      },
    ],
    links: {
      breadcrumbs: [],
      crossSell: [],
      crossSellSKUs: [],
      related: [],
      relatedSKUs: [],
      similar: [],
      upSell: [],
      upSellSKUs: [],
    },
    mediaGallery: [
      {
        description: 'A long term review of the iRobot...',
        id: '1269553',
        metadata: '',
        provider: '',
        storeId: 'en',
        title: 'Roomba i7+ Review - 6 Months Later',
        type: 'VIDEO',
        types: [],
        url: 'https://www.youtube.com/watch?v=7NW1BxPuwAk',
      },
      {
        description: '',
        id: '102080',
        metadata: '',
        provider: '',
        storeId: '',
        title: 'ลิปสติก Rouge G de Guerlain Lipstick Refill สีN°214 ขนาด 3.5 กรัม',
        type: 'IMAGE',
        types: [[]],
        url: 'secureBaseMediaUrl/catalog/product/C/D/CDS16533073.jpg',
      },
      {
        description: '',
        id: '102081',
        metadata: '',
        provider: '',
        storeId: '',
        title: 'ลิปสติก Rouge G de Guerlain Lipstick Refill สีN°214 ขนาด 3.5 กรัม',
        type: 'IMAGE',
        types: [],
        url: 'secureBaseMediaUrl/catalog/product/C/D/CDS16533073_x2.jpg',
      },
    ],
    name: 'ลิปสติก Rouge G de Guerlain Lipstick Refill สีN°214 ขนาด 3.5 กรัม',
    options: [],
    overlayImageUrl: null,
    paymentMethods: [],
    preorder: null,
    priceSummary: {
      discount: null,
      final: 20,
      original: 20,
    },
    promotionTag: null,
    promotions: [
      {
        description: 'TEST',
        effectiveDateRange: {
          from: '2018-11-25T17:00:00.000Z',
          to: null,
        },
        id: 'TEST',
        title: 'TEST',
      },
      {
        description: 'buy more than 1000 discount 50฿',
        effectiveDateRange: {
          from: '2020-03-23T17:00:00.000Z',
          to: null,
        },
        id: 'buy more than 2000 discount 50฿',
        title: 'buy more than 2000 discount 50฿',
      },
    ],
    purchaseLimit: {
      quantity: {
        max: 999,
        min: 1,
      },
    },
    rating: {
      average: 5,
      totalVoteCount: 1,
      fiveStar: 1,
      fourStar: 0,
      oneStar: 0,
      roundedRating: 5,
      threeStar: 0,
      twoStar:0,
    },
    reviews: [],
    seller: {
      id: 'cds',
      name: 'Central Department Store',
    },
    shippingMethods: ['SAME_DAY_DELIVERY', 'NEXT_DAY_DELIVERY'],
    shortDescription: '',
    sku: 'CDS16533073',
    the1Redemption: {
      earnPoint: 1,
      redeemPoint: 160,
    },
    thumbnailUrl: 'secureBaseMediaUrl/catalog/product/C/D/CDS16533073.jpg',
    type: 'simple',
    urlKey: 'guerlain-rouge-g-de-guerlain-lipstick-refill-n0214-3-5-cds16533073',
  },
];

const mockProductSimilarResponse = [
  {
    sku: 'grcds13892876',
    type: 'configurable',
    children: [
      {
        product: {
          sku: 'CDS14353420',
        },
      },
      {
        product: {
          sku: 'CDS14353390',
        },
      },
    ],
  },
  {
    sku: 'CDS14281945',
  },
  {
    sku: 'CDS13956882',
  },
  {
    sku: 'CDS12635450',
  },
  {
    sku: 'CDS21103643',
  },
];

const mockProductSimilarResult1 = {
  products: [
    {
      sku: 'CDS12635450',
    },
    {
      sku: 'CDS21103643',
    },
    {
      sku: 'grcds13892876',
      type: 'configurable',
      children: [
        {
          product: {
            sku: 'CDS14353420',
          },
        },
        {
          product: {
            sku: 'CDS14353390',
          },
        },
      ],
    },
  ],
  totalCount: 4,
};

const mockProductAssociationResponse1 = {
  totalCount: 4,
  products: [
    {
      sku: 'grcds13892876',
      type: 'configurable',
      children: [
        {
          product: {
            sku: 'CDS14353420',
          },
        },
        {
          product: {
            sku: 'CDS14353390',
          },
        },
      ],
    },
    {
      sku: 'CDS14281945',
    },
    {
      sku: 'CDS13956882',
    },
  ],
};

const mockProductSimilarResult2 = {
  products: [
    {
      sku: 'CDS12635450',
    },
    {
      sku: 'CDS21103643',
    },
    {
      sku: 'grcds13892876',
      type: 'configurable',
      children: [
        {
          product: {
            sku: 'CDS14353420',
          },
        },
        {
          product: {
            sku: 'CDS14353390',
          },
        },
      ],
    },
    {
      sku: 'CDS14281945',
    },
    {
      sku: 'CDS13956882',
    },
  ],
  totalCount: 4,
};

const mockProductAssociationResponse2 = {
  totalCount: 4,
  products: [
    {
      sku: 'grcds13892876',
      type: 'configurable',
      children: [
        {
          product: {
            sku: 'CDS14353420',
          },
        },
        {
          product: {
            sku: 'CDS14353390',
          },
        },
      ],
    },
    {
      sku: 'CDS14281945',
    },
    {
      sku: 'CDS13956882',
    },
    {
      sku: 'CDS12635450',
    },
    {
      sku: 'CDS21103643',
    },
  ],
};

const mockProductSimilarResult3 = { products: [], totalCount: 0 };

const mockDataFindById = { id: 'ID', name: 'Product 1' };

export {
  mockFilterRatingOptionsMDC,
  mockFilterRatingOptions,
  mockFilterBrandNameOptionsTransform,
  mockFilterAgeRangeOptionsTransform,
  mockFilterColorOptionsTransform,
  mockFilterBrandNameOptionsResult,
  mockFilterAgeRangeOptionsResult,
  mockFilterColorOptionsResult,
  mockDataFindByIdOrSku,
  mockProductDetailCSResponse,
  mockProductDetailResult,
  mockProductDetailResponse,
  mockProductDetailResponse2,
  mockProductData,
  mockStoreConfig,
  mockSuggestPromotion,
  mockDataFindBySKUsNew,
  mockResponseFindBySKUsNew,
  mockProductSimilarResponse,
  mockProductSimilarResult1,
  mockProductSimilarResult2,
  mockProductSimilarResult3,
  mockProductAssociationResponse1,
  mockProductAssociationResponse2,
  mockDataFindById,
};
