export const mockCustomerAddressesEmpty = {
  addresses: [],
};

export const mockCustomerAddresses = {
  addresses: [
    {
      id: 3773,
      customer_id: 3633,
      region: { region_code: 'bkk', region: 'กรุงเทพมหานคร', region_id: 570 },
      region_id: 570,
      country_id: 'TH',
      street: ['n/a'],
      telephone: '0123123312',
      postcode: '10170',
      city: 'n/a',
      firstname: 'waa',
      lastname: 'a',
      default_shipping: true,
      custom_attributes: [
        { attribute_code: 'customer_address_type', value: 'shipping', name: 'customer_address_type' },
        { attribute_code: 'address_name', value: 'home', name: 'address_name' },
        { attribute_code: 'address_line', value: '24/34', name: 'address_line' },
        { attribute_code: 'district', value: 'ตลิ่งชัน', name: 'district' },
        { attribute_code: 'district_id', value: '18', name: 'district_id' },
        { attribute_code: 'subdistrict', value: 'ตลิ่งชัน', name: 'subdistrict' },
        { attribute_code: 'subdistrict_id', value: '88', name: 'subdistrict_id' },
        { attribute_code: 'full_tax_type', value: 'personal', name: 'full_tax_type' },
      ],
    },
    {
      id: 3779,
      customer_id: 3633,
      region: { region_code: 'bkk', region: 'กรุงเทพมหานคร', region_id: 570 },
      region_id: 570,
      country_id: 'TH',
      street: ['n/a'],
      telephone: '012312123',
      postcode: '10170',
      city: 'n/a',
      firstname: 'asdasd',
      lastname: 'wdqwd',
      vat_id: '1839900237332',
      custom_attributes: [
        { attribute_code: 'customer_address_type', value: 'billing', name: 'customer_address_type' },
        { attribute_code: 'address_line', value: 'adq', name: 'address_line' },
        { attribute_code: 'district', value: 'ตลิ่งชัน', name: 'district' },
        { attribute_code: 'district_id', value: '18', name: 'district_id' },
        { attribute_code: 'subdistrict', value: 'คลองชักพระ', name: 'subdistrict' },
        { attribute_code: 'subdistrict_id', value: '86', name: 'subdistrict_id' },
        { attribute_code: 'full_tax_type', value: 'personal', name: 'full_tax_type' },
      ],
    },
  ],
};

export const mockAddressesResult = [
  {
    id: '3773',
    firstName: 'waa',
    lastName: 'a',
    telephone: '0123123312',
    postcode: '10170',
    countryId: 'TH',
    subDistrict: { id: '88', name: 'ตลิ่งชัน' },
    district: { id: '18', name: 'ตลิ่งชัน' },
    province: { id: '570', code: 'bkk', name: 'กรุงเทพมหานคร' },
    isDefaultBilling: false,
    isDefaultShipping: true,
    isFullTaxRequest: false,
    customerAddressType: 'SHIPPING',
    addressLine: '24/34',
    addressName: 'home',
    building: '',
    branchId: '',
    remark: '',
    houseNo: '',
    fax: '',
    soi: '',
    villageName: '',
    road: '',
    moo: '',
    buildingType: '',
    telMobile: '',
    lat: '',
    lng: '',
    fullTaxType: 'PERSONAL',
  },
  {
    id: '3779',
    firstName: 'asdasd',
    lastName: 'wdqwd',
    telephone: '012312123',
    postcode: '10170',
    countryId: 'TH',
    vatId: '1839900237332',
    subDistrict: { id: '86', name: 'คลองชักพระ' },
    district: { id: '18', name: 'ตลิ่งชัน' },
    province: { id: '570', code: 'bkk', name: 'กรุงเทพมหานคร' },
    isDefaultBilling: false,
    isDefaultShipping: false,
    isFullTaxRequest: false,
    customerAddressType: 'BILLING',
    addressLine: 'adq',
    addressName: '',
    building: '',
    branchId: '',
    remark: '',
    houseNo: '',
    fax: '',
    soi: '',
    villageName: '',
    road: '',
    moo: '',
    buildingType: '',
    telMobile: '',
    lat: '',
    lng: '',
    fullTaxType: 'PERSONAL',
  },
];
