export const mockProductRecommendationByUserDataLakeResponse = [
  {
    id: 1,
    data: [
      {
        item: ['CDS16155824', ' CDS16155879 ', ' CDS16481862'],
      },
    ],
  },
];

export const mockProductRecommendationBySkuDataLakeResponse1 = [
  {
    id: 1,
    name: 'สินค้าที่คล้ายกัน',
    data: [
      {
        item: ['CDS5391899', 'CDS16564060'],
        code: 'same_brand',
      },
      {
        item: ['CDS13261481', 'CDS13345242'],
        code: 'diff_brand',
      },
    ],
    filler: ['CDS3684511', 'CDS22885609'],
  },
  {
    id: 2,
    name: 'You May Like',
    data: [
      {
        item: ['CDS16155824', ' CDS16155879 ', ' CDS16481862'],
        code: 'product_asso',
      },
    ],
    filler: [],
  },
];

export const mockProductRecommendationBySkuDataLakeResponse2 = [
  {
    id: 1,
    name: 'สินค้าที่คล้ายกัน',
    data: [
      {
        item: ['CDS5391899', 'CDS16564060'],
        code: 'same_brand',
      },
      {
        item: ['CDS13261481', 'CDS13345242'],
        code: 'diff_brand',
      },
    ],
    filler: ['CDS3684511', 'CDS22885609'],
  },
];

export const mockProductRecommendationBySkuDataLakeResponse3 = [
  {
    id: 2,
    name: 'You May Like',
    data: [
      {
        item: ['CDS16155824', ' CDS16155879 ', ' CDS16481862'],
        code: 'another_code',
      },
    ],
    filler: [],
  },
];

export const mockPayloadLegacySearchSkus1 = {
  filter: {
    inFilters: [
      { filterBy: 'VISIBILITY', filterValues: ['2', '4'] },
      { filterBy: 'SKU', filterValues: ['CDS16155824', 'CDS16155879', 'CDS16481862'] },
    ],
  },
};

export const mockPayloadLegacySearchSkus2 = {
  filter: {
    inFilters: [
      { filterBy: 'VISIBILITY', filterValues: ['2', '4'] },
      { filterBy: 'SKU', filterValues: [] },
    ],
  },
};

export const mockShippingMethodFlagsResult = [
  'STANDARD_PICK_UP',
  'STANDARD_DELIVERY',
  'SAME_DAY_DELIVERY',
  'NEXT_DAY_DELIVERY',
];

const shipping_delivery_methods = [
  {
    delivery_method: 'Standard Pickup',
    delivery_method_code: 'click_and_collect',
    shipping_method: 'รับเวลาปกติ',
    shipping_method_code: 'pickupatstore_pickupatstore',
  },
  {
    delivery_method: '2 Hour Pickup',
    delivery_method_code: 'hour_pickup',
    shipping_method: 'รับใน 2 ชม.',
    shipping_method_code: 'storepickup_ispu',
  },
  {
    delivery_method: 'Standard Delivery',
    delivery_method_code: 'delivery',
    shipping_method: 'จัดส่งปกติ',
    shipping_method_code: 'cds_standard',
  },
  {
    delivery_method: 'Express Delivery',
    delivery_method_code: 'express_delivery',
    shipping_method: 'จัดส่งภายในวัน',
    shipping_method_code: 'cds_same_day',
  },
  {
    delivery_method: 'Express Delivery',
    delivery_method_code: 'express_delivery',
    shipping_method: 'จัดส่งวันถัดไป',
    shipping_method_code: 'cds_next_day',
  },
  {
    delivery_method: '3 Hour Delivery',
    delivery_method_code: 'ship_from_store',
    shipping_method: '3 Hours Delivery',
    shipping_method_code: 'grab_ship_from_store',
  },
];

const shipping_delivery_methods_rbs = [
  {
    delivery_method: 'Standard Pickup',
    delivery_method_code: 'click_and_collect',
    shipping_method: 'รับเวลาปกติ',
    shipping_method_code: 'pickupatstore_pickupatstore',
  },
  {
    delivery_method: '2 Hour Pickup',
    delivery_method_code: 'hour_pickup',
    shipping_method: 'รับใน 2 ชม.',
    shipping_method_code: 'storepickup_ispu',
  },
  {
    delivery_method: 'Standard Delivery',
    delivery_method_code: 'delivery',
    shipping_method: 'จัดส่งปกติ',
    shipping_method_code: 'rbs_standard',
  },
  {
    delivery_method: 'Express Delivery',
    delivery_method_code: 'express_delivery',
    shipping_method: 'จัดส่งภายในวัน',
    shipping_method_code: 'rbs_same_day',
  },
  {
    delivery_method: 'Express Delivery',
    delivery_method_code: 'express_delivery',
    shipping_method: 'จัดส่งวันถัดไป',
    shipping_method_code: 'rbs_next_day',
  },
  {
    delivery_method: '3 Hour Delivery',
    delivery_method_code: 'ship_from_store',
    shipping_method: '3 Hours Delivery',
    shipping_method_code: 'grab_ship_from_store',
  },
];

const mockCartPriceRuleOverlays = [
  {
    rule_id: '983',
    product_id: '44051',
    overlay_image: 'salesrule_overlay/26e178f_1.png',
    display_priority: '1',
  },
];

const mockCartPriceRuleOverlaysTransform = [
  {
    id: '983',
    overlay_image: 'salesrule_overlay/26e178f_1.png',
    display_priority: 1,
  },
];

export const mockLegacySearchResponse1 = {
  products: [
    {
      id: '255099',
      sku: 'GRMKPCO008849213',
      name: 'Highlighter Contour0008_resync Edit',
      status: 1,
      visibility: '4',
      type_id: 'configurable',
      created_at: '2019-09-24 08:51:18',
      updated_at: '2020-05-19 07:33:45',
      brand_name: 'DIOR',
      brand_url: 'dior',
      image: null,
      url_key: 'dior-highlighter-contour0008-resync-edit-grmkpco008849213',
      is_in_stock: true,
      price: 0,
      special_price: null,
      special_from_date: null,
      special_to_date: null,
      discount_amount: null,
      new_tag: '1',
      only_at_tag: '0',
      promo_tag: null,
      online_exclusive_tag: '0',
      recommended: '1',
      best_sellers: '0',
      collection: null,
      min_sale_qty: 1,
      max_sale_qty: 200,
      preorder_shipping_date: null,
      product_type: null,
      flash_deal: '0',
      flash_deal_qty: null,
      flash_deal_sold_qty: null,
      flash_deal_from: null,
      flash_deal_to: null,
      marketplace_product_type_option: null,
      marketplace_seller_option: null,
      color_group_name: null,
      size: null,
      homepage_new: '0',
      news_from_date: null,
      overall_rating: {
        rating_id: true,
        rating: 3.4901960784314,
        category: 'true',
        option_id: true,
        total_vote: 51,
        five_star: 0,
        four_star: 25,
        three_star: 26,
        two_star: 0,
        one_star: 0,
        rounded_rating: 3.5,
      },
      overlay: null,
      breadcrumbs: [
        { category_id: '3060', level: '1', name: 'Beauty', url: 'beauty' },
        { category_id: '3092', level: '2', name: 'makeup', url: 'beauty/makeup' },
        { category_id: '3093', level: '3', name: 'face', url: 'beauty/makeup/face' },
        { category_id: '3100', level: '4', name: 'highlighter_contour', url: 'beauty/makeup/face/highlighter-contour' },
      ],
      categories: [
        { id: '3060', name: 'Beauty', parent_id: '260', url_path: 'beauty' },
        { id: '3092', name: 'makeup', parent_id: '3060', url_path: 'beauty/makeup' },
        { id: '3093', name: 'face', parent_id: '3092', url_path: 'beauty/makeup/face' },
        {
          id: '3100',
          name: 'highlighter_contour',
          parent_id: '3093',
          url_path: 'beauty/makeup/face/highlighter-contour',
        },
      ],
      configurable_product_links: ['254862'],
      configurable_products: [
        {
          id: '254862',
          sku: 'MKP0063593',
          name: 'Highlighter Contour0008_resync Edit',
          status: 1,
          visibility: '1',
          type_id: 'simple',
          created_at: '2019-09-23 07:45:40',
          updated_at: '2020-10-14 03:43:09',
          brand_name: 'DIOR',
          brand_url: 'dior',
          image:
            '/h/t/httpss3-ap-southeast-1.amazonaws.compim-uat-product-images9d989d981c2ba1908fe61dd72235a8cd8eea2cc921ee_5c2a18e007994c929dbfb9c25c1992a4dummy.jpg',
          url_key: 'dior-highlighter-contour0008-mkp0063593',
          is_in_stock: true,
          price: 500,
          special_price: 300,
          special_from_date: '2020-08-31 00:00:00',
          special_to_date: null,
          discount_amount: null,
          new_tag: '0',
          only_at_tag: '0',
          promo_tag: null,
          online_exclusive_tag: '0',
          recommended: '0',
          best_sellers: '0',
          collection: null,
          min_sale_qty: 1,
          max_sale_qty: 200,
          preorder_shipping_date: null,
          product_type: null,
          flash_deal: '0',
          flash_deal_qty: null,
          flash_deal_sold_qty: '1',
          flash_deal_from: '2020-03-26 06:10:00',
          flash_deal_to: '2020-07-26 13:10:00',
          marketplace_product_type_option: 'Marketplace',
          marketplace_seller_option: 'Looknam MKP 3PL',
          size: null,
          color_group_name: null,
          overlay: null,
          breadcrumbs: [
            { category_id: '3060', level: '1', name: 'Beauty', url: 'beauty' },
            { category_id: '3092', level: '2', name: 'makeup', url: 'beauty/makeup' },
            { category_id: '3093', level: '3', name: 'face', url: 'beauty/makeup/face' },
            {
              category_id: '3100',
              level: '4',
              name: 'highlighter_contour',
              url: 'beauty/makeup/face/highlighter-contour',
            },
          ],
          categories: [
            { id: '3060', name: 'Beauty', parent_id: '260', url_path: 'beauty' },
            { id: '3093', name: 'face', parent_id: '3092', url_path: 'beauty/makeup/face' },
            {
              id: '3100',
              name: 'highlighter_contour',
              parent_id: '3093',
              url_path: 'beauty/makeup/face/highlighter-contour',
            },
            { id: '3092', name: 'makeup', parent_id: '3060', url_path: 'beauty/makeup' },
          ],
        },
      ],
      configurable_product_options: [
        {
          attribute_id: '410',
          label: 'Shade',
          values: [
            {
              value_index: 3787,
              extension_attributes: {
                frontend_type: 'swatch_color',
                frontend_value: '#8f298f',
                label: 'None',
                products: ['254862'],
              },
            },
          ],
        },
      ],
    },
  ],
};
export const mockLegacySearchResponse2 = {
  products: [
    {
      online_salable: true,
      offline_salable: true,
      shipping_delivery_methods: null,
    },
  ],
};

export const mockLegacySearchResponse3 = {
  products: [
    {
      type_id: 'configurable',
      online_salable: true,
      offline_salable: true,
      shipping_delivery_methods,
      configurable_products: [
        {
          online_salable: true,
          offline_salable: false,
          shipping_delivery_methods,
        },
      ],
    },
  ],
};

export const mockLegacySearchResponse4 = {
  products: [
    {
      type_id: 'configurable',
      online_salable: true,
      offline_salable: true,
      shipping_delivery_methods: shipping_delivery_methods_rbs,
      configurable_products: [
        {
          online_salable: true,
          offline_salable: false,
          shipping_delivery_methods: shipping_delivery_methods_rbs,
        },
      ],
    },
  ],
};

export const mockSearchResult1 = {
  products: [
    {
      id: '255099',
      sku: 'GRMKPCO008849213',
      name: 'Highlighter Contour0008_resync Edit',
      status: 1,
      visibility: '4',
      type_id: 'configurable',
      created_at: '2019-09-24 08:51:18',
      updated_at: '2020-05-19 07:33:45',
      brand_name: 'DIOR',
      brand_url: 'dior',
      image: null,
      url_key: 'dior-highlighter-contour0008-resync-edit-grmkpco008849213',
      is_in_stock: true,
      price: 0,
      special_price: null,
      special_from_date: null,
      special_to_date: null,
      discount_amount: null,
      new_tag: '1',
      only_at_tag: '0',
      promo_tag: null,
      online_exclusive_tag: '0',
      recommended: '1',
      best_sellers: '0',
      collection: null,
      min_sale_qty: 1,
      max_sale_qty: 200,
      preorder_shipping_date: null,
      product_type: null,
      flash_deal: '0',
      flash_deal_qty: null,
      flash_deal_sold_qty: null,
      flash_deal_from: null,
      flash_deal_to: null,
      marketplace_product_type_option: null,
      marketplace_seller_option: null,
      color_group_name: null,
      size: null,
      homepage_new: '0',
      news_from_date: null,
      overall_rating: {
        rating_id: true,
        rating: 3.4901960784314,
        category: 'true',
        option_id: true,
        total_vote: 51,
        five_star: 0,
        four_star: 25,
        three_star: 26,
        two_star: 0,
        one_star: 0,
        rounded_rating: 3.5,
      },
      overlay: null,
      breadcrumbs: [
        {
          category_id: '3060',
          level: '1',
          name: 'Beauty',
          url: 'beauty',
        },
        {
          category_id: '3092',
          level: '2',
          name: 'makeup',
          url: 'beauty/makeup',
        },
        {
          category_id: '3093',
          level: '3',
          name: 'face',
          url: 'beauty/makeup/face',
        },
        {
          category_id: '3100',
          level: '4',
          name: 'highlighter_contour',
          url: 'beauty/makeup/face/highlighter-contour',
        },
      ],
      categories: [
        {
          id: '3060',
          name: 'Beauty',
          parent_id: '260',
          url_path: 'beauty',
        },
        {
          id: '3092',
          name: 'makeup',
          parent_id: '3060',
          url_path: 'beauty/makeup',
        },
        {
          id: '3093',
          name: 'face',
          parent_id: '3092',
          url_path: 'beauty/makeup/face',
        },
        {
          id: '3100',
          name: 'highlighter_contour',
          parent_id: '3093',
          url_path: 'beauty/makeup/face/highlighter-contour',
        },
      ],
      configurable_product_links: ['254862'],
      configurable_products: [
        {
          id: '254862',
          sku: 'MKP0063593',
          name: 'Highlighter Contour0008_resync Edit',
          status: 1,
          visibility: '1',
          type_id: 'simple',
          created_at: '2019-09-23 07:45:40',
          updated_at: '2020-10-14 03:43:09',
          brand_name: 'DIOR',
          brand_url: 'dior',
          image:
            '/h/t/httpss3-ap-southeast-1.amazonaws.compim-uat-product-images9d989d981c2ba1908fe61dd72235a8cd8eea2cc921ee_5c2a18e007994c929dbfb9c25c1992a4dummy.jpg',
          url_key: 'dior-highlighter-contour0008-mkp0063593',
          is_in_stock: true,
          price: 500,
          special_price: 300,
          special_from_date: '2020-08-31 00:00:00',
          special_to_date: null,
          discount_amount: null,
          new_tag: '0',
          only_at_tag: '0',
          promo_tag: null,
          online_exclusive_tag: '0',
          recommended: '0',
          best_sellers: '0',
          collection: null,
          min_sale_qty: 1,
          max_sale_qty: 200,
          preorder_shipping_date: null,
          product_type: null,
          flash_deal: '0',
          flash_deal_qty: null,
          flash_deal_sold_qty: '1',
          flash_deal_from: '2020-03-26 06:10:00',
          flash_deal_to: '2020-07-26 13:10:00',
          marketplace_product_type_option: 'Marketplace',
          marketplace_seller_option: 'Looknam MKP 3PL',
          size: null,
          color_group_name: null,
          overlay: null,
          breadcrumbs: [
            {
              category_id: '3060',
              level: '1',
              name: 'Beauty',
              url: 'beauty',
            },
            {
              category_id: '3092',
              level: '2',
              name: 'makeup',
              url: 'beauty/makeup',
            },
            {
              category_id: '3093',
              level: '3',
              name: 'face',
              url: 'beauty/makeup/face',
            },
            {
              category_id: '3100',
              level: '4',
              name: 'highlighter_contour',
              url: 'beauty/makeup/face/highlighter-contour',
            },
          ],
          categories: [
            {
              id: '3060',
              name: 'Beauty',
              parent_id: '260',
              url_path: 'beauty',
            },
            {
              id: '3093',
              name: 'face',
              parent_id: '3092',
              url_path: 'beauty/makeup/face',
            },
            {
              id: '3100',
              name: 'highlighter_contour',
              parent_id: '3093',
              url_path: 'beauty/makeup/face/highlighter-contour',
            },
            {
              id: '3092',
              name: 'makeup',
              parent_id: '3060',
              url_path: 'beauty/makeup',
            },
          ],
          cart_price_rule_overlays: mockCartPriceRuleOverlaysTransform,
        },
      ],
      configurable_product_options: [
        {
          attribute_id: '410',
          label: 'Shade',
          values: [
            {
              value_index: 3787,
              extension_attributes: {
                frontend_type: 'swatch_color',
                frontend_value: '#8f298f',
                label: 'None',
                products: ['254862'],
              },
            },
          ],
        },
      ],
      cart_price_rule_overlays: mockCartPriceRuleOverlaysTransform,
      shipping_method_flags: [],
    },
  ],
};

export const mockGetSaleRuleOverlaysResponse = mockCartPriceRuleOverlays;

export const mockFindProductDetailByIdNewResponse1 = {
  suggest_promotions: [
    {
      promotion_name: 'TEST',
      full_condition: 'TEST',
      start_datetime: '2018-11-26',
      end_datetime: 'true',
      label: 'Buy 1000  get free item',
      short_description: 'TEST',
    },
    {
      promotion_name: 'buy more than 2000 discount 50฿',
      full_condition: 'buy more than 1000 discount 50฿',
      start_datetime: '2020-03-24',
      end_datetime: 'true',
      label: 'AUT - buy > = 2000 discount 50฿',
      short_description: 'buy more than 2000 discount 50฿',
    },
  ],
  configurable_products: null,
  shipping_delivery_methods: null,
  configurable_product_options: null,
  id: '7121',
  sku: 'CDS15872296',
  name: 'เสื้อเชิ้ตแขนยาว สีน้ำเงิน ไซส์ XXL',
  price: 20,
  breadcrumbs: [
    { category_id: '3053', level: '1', name: 'ผู้ชาย', url: 'men' },
    { category_id: '4662', level: '4', name: 'เสื้อเชิ้ต', url: 'men/shop-by-style/formal/shirts' },
  ],
  categories: [
    { name: 'formal', parent_id: '5636', id: '5637', url_path: 'root/men/clothing/shirts/formal' },
    { name: 'shirts', parent_id: '5635', id: '5636', url_path: 'root/men/clothing/shirts' },
    { name: 'clothing', parent_id: '5634', id: '5635', url_path: 'root/men/clothing' },
    { name: 'men', parent_id: '5451', id: '5634', url_path: 'root/men' },
    { name: null, parent_id: null, id: '5451', url_path: null },
    { name: null, parent_id: null, id: '260', url_path: null },
    { name: 'เชิ้ตทางการ', parent_id: '4700', id: '4701', url_path: 'men/jacket/shirts/formal' },
    { name: 'เสื้อเชิ้ต', parent_id: '4654', id: '4700', url_path: 'men/jacket/shirts' },
    { name: null, parent_id: null, id: '4654', url_path: null },
    { name: 'ผู้ชาย', parent_id: '260', id: '3053', url_path: 'men' },
    { name: 'เสื้อเชิ้ต', parent_id: '4661', id: '4662', url_path: 'men/shop-by-style/formal/shirts' },
    { name: null, parent_id: null, id: '4661', url_path: null },
    { name: null, parent_id: null, id: '4660', url_path: null },
  ],
  status: 1,
  visibility: '4',
  type_id: 'simple',
  created_at: '2018-08-14 12:35:59',
  configurable_product_links: null,
  brand_id: '365',
  brand_name: 'GQ',
  brand_url: 'gq',
  color_shade_name: 'กรมท่า',
  color_group_name: ['ฟ้า/น้ำเงิน'],
  image: '/C/D/CDS15872296.jpg',
  url_key: 'gq-long-sleeve-shirt-navy-size-xxl-cds15872296',
  special_price: null,
  special_from_date: null,
  special_to_date: null,
  is_in_stock: true,
  new_tag: null,
  only_at_tag: '0',
  promo_tag: null,
  recommended: null,
  flash_deal: null,
  discount_amount: null,
  updated_at: '2019-12-17 11:00:34',
  product_type: 'Normal',
  preorder_shipping_date: null,
  max_sale_qty: 200,
  min_sale_qty: 1,
  collection: null,
  online_exclusive_tag: '0',
  marketplace_product_type_option: null,
  marketplace_seller_option: null,
  flash_deal_enable: null,
  flash_deal_qty: null,
  flash_deal_sold_qty: null,
  flash_deal_from: null,
  flash_deal_to: null,
  is_hide_original_price: null,
  is_show_special_product_name: null,
  news_from_date: null,
  overlay: null,
  ranking: null,
  flash_deal_position: null,
  recommened_sort_order: null,
  manual_boosting: null,
  size: 'XXL',
  allow_cc: '1',
  allow_cod: null,
  allow_express: '0',
  allow_gift_wrapping: '1',
  allow_installment: '0',
  allow_return: '0',
  bu: 'CDS',
  color: null,
  color_shade_id: '752',
  gift_message_available: null,
  gift_wrapping_available: null,
  installment_plans: null,
  homepage_new: null,
  manage_stock: true,
  min_qty: 0,
  payment_methods: null,
  product_id: 7121,
  product_links: null,
  product_sell_type: '445',
  product_status: null,
  shipping_methods: null,
  size_type: null,
  stock_id: 1,
  t1c_earn_points_estimate: [1],
  t1c_redeemable_points: [160],
  thumbnail: '/C/D/CDS15872296.jpg',
  online_salable: true,
  offline_salable: false,
  media_gallery_entries: [
    {
      id: '14039',
      types: ['image', 'small_image', 'thumbnail'],
      file: '/C/D/CDS15872296.jpg',
      media_type: 'image',
      label: true,
      position: '1',
      disabled: false,
    },
    {
      id: '14040',
      types: [],
      file: '/C/D/CDS15872296_x2.jpg',
      media_type: 'image',
      label: true,
      position: '2',
      disabled: false,
    },
  ],
  marketplace: null,
  overall_rating: {
    rating_id: 1,
    rating: 0,
    category: '1',
    option_id: 1,
    total_vote: 0,
    five_star: 0,
    four_star: 0,
    three_star: 0,
    two_star: 0,
    one_star: 0,
    rounded_rating: null,
  },
  brand: {
    brand_id: 365,
    name: 'GQ',
    website_ids: [1],
    url_key: 'gq',
    logo: null,
    is_featured: false,
    extension_attributes: {
      menu_css: null,
      parent_category: 260,
      position: 0,
      product_count: 42,
      product_name_special: false,
      hide_product_original_price: false,
      hide_t1c_redeemable_amount: false,
      allow_product_review: false,
    },
  },
  description:
    '<p>เผยเสน่ห์แบบหนุ่มสุดเนี๊ยบ ด้วยเสื้อเชิ้ตแขนยาวจากแบรนด์ GQ<br/>ที่มาในดีไซน์เรียบหรู และทันสมัย เหมาะสำหรับไลฟ์สไตล์คนรุ่นใหม่ ผลิตจากเนื้อผ้าชั้นดี ผ่านการตัดเย็บที่พิถีพิถัน สวมใส่สบาย เพิ่มความมั่นใจในทุกวันของคุณ<br/>ดีไซน์เสื้อคอปก แขนยาว<br/>ทรง Modern Fit<br/>ผลิตจากเนื้อผ้าคอตตอน 100%<br/>สวมใส่สบาย<br/>ไซส์ XXL<br/>รอบอก 48 นิ้ว<br/>รอบเอว 44 นิ้ว<br/>ความยาวแขนเสื้อ 35 นิ้ว<br/>ความยาว 31 นิ้ว<br/>สีน้ำเงิน<br/>ตรวจสอบไซส์ Size chart ที่ลิ้งค์ด้านบน"{color:blue}พบสินค้าเพิ่มเติมจาก GQ คลิก!(http://www.central.co.th/gq)":http://www.central.co.th/gq%{color:red}หมายเหตุ: สีของผลิตภัณฑ์ที่แสดงบนเว็บไซต์อาจมีความแตกต่างกัน จากการตั้งค่าการแสดงผลของแต่ละหน้าจอ%<br/><ul><li>สี : น้ำเงิน</li><li>โอกาสที่สวมใส่ : ทางการ, ทำงาน, ลำลอง</li><li>เหมาะกับกิจกรรม : ทั่วไป, อื่นๆ</li><li>ไซส์ : XXL </li><li>คอเสื้อ : คอปก</li><li>แขนเสื้อ : แขนยาว</li></ul></p><p><b>หมายเหตุ: สีของผลิตภัณฑ์ที่แสดงบนเว็บไซต์อาจมีความแตกต่างกันจากการตั้งค่าการแสดงผลสีของแต่ละหน้าจอ</b></p>',
  short_description: null,
  meta_description:
    'ซื้อ GQ เสื้อเชิ้ตแขนยาว สีน้ำเงิน ไซส์ XXL ได้เลยที่นี่ รับประกันสินค้าของแท้แน่นอน100% เช็คส่วนลดและสิทธิพิเศษต่างๆอีกมากมายได้เลยที่ Central.co.th',
  meta_keyword: null,
  meta_title: 'GQ เสื้อเชิ้ตแขนยาว สีน้ำเงิน ไซส์ XXL | Central.co.th',
  category_paths: [
    { parent_id: '5636', category_id: '5637', name: 'formal', level: '6' },
    { parent_id: '5635', category_id: '5636', name: 'shirts', level: '5' },
    { parent_id: '5634', category_id: '5635', name: 'clothing', level: '4' },
    { parent_id: '5451', category_id: '5634', name: 'men', level: '3' },
    { parent_id: '260', category_id: '5451', name: null, level: '2' },
    { parent_id: '1', category_id: '260', name: null, level: '1' },
    { parent_id: '4700', category_id: '4701', name: 'เชิ้ตทางการ', level: '5' },
    { parent_id: '4654', category_id: '4700', name: 'เสื้อเชิ้ต', level: '4' },
    { parent_id: '3053', category_id: '4654', name: null, level: '3' },
    { parent_id: '260', category_id: '3053', name: 'ผู้ชาย', level: '2' },
    { parent_id: '4661', category_id: '4662', name: 'เสื้อเชิ้ต', level: '5' },
    { parent_id: '4660', category_id: '4661', name: null, level: '4' },
    { parent_id: '3053', category_id: '4660', name: null, level: '3' },
  ],
  extension_attributes_installment_plans: null,
  reviews: null,
};

export const mockFindProductDetailByIdNewResult1 = {
  id: '7121',
  sku: 'CDS15872296',
  name: 'เสื้อเชิ้ตแขนยาว สีน้ำเงิน ไซส์ XXL',
  price: 20,
  breadcrumbs: [
    { category_id: '3053', level: '1', name: 'ผู้ชาย', url: 'men' },
    { category_id: '4662', level: '4', name: 'เสื้อเชิ้ต', url: 'men/shop-by-style/formal/shirts' },
  ],
  status: 1,
  visibility: '4',
  type_id: 'simple',
  created_at: '2018-08-14 12:35:59',
  updated_at: '2019-12-17 11:00:34',
  product_links: null,
  media_gallery_entries: [
    {
      id: '14039',
      types: ['image', 'small_image', 'thumbnail'],
      file: '/C/D/CDS15872296.jpg',
      media_type: 'image',
      label: true,
      position: '1',
      disabled: false,
    },
    {
      id: '14040',
      types: [],
      file: '/C/D/CDS15872296_x2.jpg',
      media_type: 'image',
      label: true,
      position: '2',
      disabled: false,
    },
  ],
  image: '/C/D/CDS15872296.jpg',
  thumbnail: '/C/D/CDS15872296.jpg',
  url_key: 'gq-long-sleeve-shirt-navy-size-xxl-cds15872296',
  description:
    '<p>เผยเสน่ห์แบบหนุ่มสุดเนี๊ยบ ด้วยเสื้อเชิ้ตแขนยาวจากแบรนด์ GQ<br/>ที่มาในดีไซน์เรียบหรู และทันสมัย เหมาะสำหรับไลฟ์สไตล์คนรุ่นใหม่ ผลิตจากเนื้อผ้าชั้นดี ผ่านการตัดเย็บที่พิถีพิถัน สวมใส่สบาย เพิ่มความมั่นใจในทุกวันของคุณ<br/>ดีไซน์เสื้อคอปก แขนยาว<br/>ทรง Modern Fit<br/>ผลิตจากเนื้อผ้าคอตตอน 100%<br/>สวมใส่สบาย<br/>ไซส์ XXL<br/>รอบอก 48 นิ้ว<br/>รอบเอว 44 นิ้ว<br/>ความยาวแขนเสื้อ 35 นิ้ว<br/>ความยาว 31 นิ้ว<br/>สีน้ำเงิน<br/>ตรวจสอบไซส์ Size chart ที่ลิ้งค์ด้านบน"{color:blue}พบสินค้าเพิ่มเติมจาก GQ คลิก!(http://www.central.co.th/gq)":http://www.central.co.th/gq%{color:red}หมายเหตุ: สีของผลิตภัณฑ์ที่แสดงบนเว็บไซต์อาจมีความแตกต่างกัน จากการตั้งค่าการแสดงผลของแต่ละหน้าจอ%<br/><ul><li>สี : น้ำเงิน</li><li>โอกาสที่สวมใส่ : ทางการ, ทำงาน, ลำลอง</li><li>เหมาะกับกิจกรรม : ทั่วไป, อื่นๆ</li><li>ไซส์ : XXL </li><li>คอเสื้อ : คอปก</li><li>แขนเสื้อ : แขนยาว</li></ul></p><p><b>หมายเหตุ: สีของผลิตภัณฑ์ที่แสดงบนเว็บไซต์อาจมีความแตกต่างกันจากการตั้งค่าการแสดงผลสีของแต่ละหน้าจอ</b></p>',
  short_description: null,
  special_price: null,
  special_from_date: null,
  special_to_date: null,
  meta_title: 'GQ เสื้อเชิ้ตแขนยาว สีน้ำเงิน ไซส์ XXL | Central.co.th',
  meta_keyword: null,
  meta_description:
    'ซื้อ GQ เสื้อเชิ้ตแขนยาว สีน้ำเงิน ไซส์ XXL ได้เลยที่นี่ รับประกันสินค้าของแท้แน่นอน100% เช็คส่วนลดและสิทธิพิเศษต่างๆอีกมากมายได้เลยที่ Central.co.th',
  custom_attributes: {
    flash_deal_enable: null,
    promo_name_tag: null,
    only_central_tag: '0',
    new: null,
    franchise: null,
    categories: [
      { name: 'formal', parent_id: '5636', id: '5637', url_path: 'root/men/clothing/shirts/formal' },
      { name: 'shirts', parent_id: '5635', id: '5636', url_path: 'root/men/clothing/shirts' },
      { name: 'clothing', parent_id: '5634', id: '5635', url_path: 'root/men/clothing' },
      { name: 'men', parent_id: '5451', id: '5634', url_path: 'root/men' },
      { name: null, parent_id: null, id: '5451', url_path: null },
      { name: null, parent_id: null, id: '260', url_path: null },
      { name: 'เชิ้ตทางการ', parent_id: '4700', id: '4701', url_path: 'men/jacket/shirts/formal' },
      { name: 'เสื้อเชิ้ต', parent_id: '4654', id: '4700', url_path: 'men/jacket/shirts' },
      { name: null, parent_id: null, id: '4654', url_path: null },
      { name: 'ผู้ชาย', parent_id: '260', id: '3053', url_path: 'men' },
      { name: 'เสื้อเชิ้ต', parent_id: '4661', id: '4662', url_path: 'men/shop-by-style/formal/shirts' },
      { name: null, parent_id: null, id: '4661', url_path: null },
      { name: null, parent_id: null, id: '4660', url_path: null },
    ],
    brand_id: '365',
    brand_name: 'GQ',
    brand_url: 'gq',
    color_group_name: ['ฟ้า/น้ำเงิน'],
    recommended: null,
    discount_amount: null,
    product_type: 'Normal',
    preorder_shipping_date: null,
    online_exclusive_tag: '0',
    flash_deal_qty: null,
    flash_deal_sold_qty: null,
    flash_deal_from: null,
    flash_deal_to: null,
    is_hide_original_price: null,
    is_show_special_product_name: null,
    news_from_date: null,
    ranking: null,
    flash_deal_position: null,
    recommened_sort_order: null,
    manual_boosting: null,
    allow_cc: '1',
    allow_cod: null,
    allow_express: '0',
    allow_gift_wrapping: '1',
    allow_installment: '0',
    allow_return: '0',
    bu: 'CDS',
    color: null,
    color_shade_id: '752',
    gift_message_available: null,
    gift_wrapping_available: null,
    homepage_new: null,
    payment_methods: null,
    product_sell_type: '445',
    product_status: null,
    shipping_methods: '',
    size_type: null,
    delivery_methods: '',
    shipping_method_flags: [],
  },
  custom_attributes_option: {
    marketplace_product_type: null,
    marketplace_seller: null,
    color_shade: 'กรมท่า',
    size: 'XXL',
    installment_plans: null,
  },
  extension_attributes: {
    category_paths: [
      { parent_id: '5636', category_id: '5637', name: 'formal', level: '6' },
      { parent_id: '5635', category_id: '5636', name: 'shirts', level: '5' },
      { parent_id: '5634', category_id: '5635', name: 'clothing', level: '4' },
      { parent_id: '5451', category_id: '5634', name: 'men', level: '3' },
      { parent_id: '260', category_id: '5451', name: null, level: '2' },
      { parent_id: '1', category_id: '260', name: null, level: '1' },
      { parent_id: '4700', category_id: '4701', name: 'เชิ้ตทางการ', level: '5' },
      { parent_id: '4654', category_id: '4700', name: 'เสื้อเชิ้ต', level: '4' },
      { parent_id: '3053', category_id: '4654', name: null, level: '3' },
      { parent_id: '260', category_id: '3053', name: 'ผู้ชาย', level: '2' },
      { parent_id: '4661', category_id: '4662', name: 'เสื้อเชิ้ต', level: '5' },
      { parent_id: '4660', category_id: '4661', name: null, level: '4' },
      { parent_id: '3053', category_id: '4660', name: null, level: '3' },
    ],
    stock_item: {
      is_in_stock: true,
      min_qty: 0,
      min_sale_qty: 1,
      max_sale_qty: 200,
      product_id: 7121,
      stock_id: 1,
      manage_stock: true,
    },
    overall_rating: {
      rating_id: 1,
      rating: 0,
      category: '1',
      option_id: 1,
      total_vote: 0,
      five_star: 0,
      four_star: 0,
      three_star: 0,
      two_star: 0,
      one_star: 0,
      rounded_rating: null,
    },
    brand: {
      brand_id: 365,
      name: 'GQ',
      website_ids: [1],
      url_key: 'gq',
      logo: null,
      is_featured: false,
      extension_attributes: {
        menu_css: null,
        parent_category: 260,
        position: 0,
        product_count: 42,
        product_name_special: false,
        hide_product_original_price: false,
        hide_t1c_redeemable_amount: false,
        allow_product_review: false,
      },
    },
    t1c_redeemable_points: [160],
    t1c_earn_points_estimate: [1],
    installment_plans: null,
    configurable_product_links: null,
    configurable_product_options: null,
    suggest_promotions: [
      {
        promotion_name: 'TEST',
        full_condition: 'TEST',
        start_datetime: '2018-11-26',
        end_datetime: 'true',
        label: 'Buy 1000  get free item',
        short_description: 'TEST',
      },
      {
        promotion_name: 'buy more than 2000 discount 50฿',
        full_condition: 'buy more than 1000 discount 50฿',
        start_datetime: '2020-03-24',
        end_datetime: 'true',
        label: 'AUT - buy > = 2000 discount 50฿',
        short_description: 'buy more than 2000 discount 50฿',
      },
    ],
    reviews: [],
  },
  marketplace: null,
  online_salable: true,
  offline_salable: false,
};

export const mockProductRecommendationBySkuCSResponse = {
  products: [
    {
      sku: 'CDS16155879',
    },
    {
      sku: 'CDS16155824',
    },
    {
      sku: 'CDS16481862',
    },
  ],
};

export const mockProductRecommendationBySkuResult = {
  products: [
    {
      sku: 'CDS16155824',
    },
    {
      sku: 'CDS16155879',
    },
    {
      sku: 'CDS16481862',
    },
  ],
};

export const mockProductRecommendationByUserCSResponse = {
  products: [
    {
      sku: 'CDS16155879',
    },
    {
      sku: 'CDS16155824',
    },
    {
      sku: 'CDS16481862',
    },
  ],
};

export const mockProductRecommendationByUserResult = {
  products: [
    {
      sku: 'CDS16155824',
    },
    {
      sku: 'CDS16155879',
    },
    {
      sku: 'CDS16481862',
    },
  ],
};
