const bannersRandomMDC = {
  id: 1,
  name: 'homepage_hero_banner',
  status: 1,
  sort_order: 0,
  page_type: 1,
  position: 3,
  product_condition: null,
  category_ids: '',
  animation_effect: 1,
  pause_time_between_transitions: 3000,
  slide_transition_speed: 500,
  is_stop_animation_mouse_on_banner: true,
  display_arrows: true,
  display_bullets: true,
  is_random_order_image: true,
  slide_ids: [344, 351, 383, 384, 385, 386, 352, 387, 388, 389],
  slide_position:
    '{"344":"0","351":"1","383":"3","384":"4","385":"5","386":"6","352":"2","387":"7","388":"8","389":"9"}',
  extension_attributes: {
    image_dir: 'aw_rbslider/slides/',
    slides: [
      {
        id: 352,
        status: 1,
        name: 'test_6',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '6.jpg',
        img_url: '',
        img_title: 'test_6',
        img_alt: 'test_6',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 383,
        status: 1,
        name: 'test_2',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_2.png',
        img_url: '',
        img_title: 'test_2',
        img_alt: 'test_2',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 384,
        status: 1,
        name: 'test_3',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_3.png',
        img_url: '',
        img_title: 'test_3',
        img_alt: 'test_3',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 385,
        status: 1,
        name: 'test_4',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_4.png',
        img_url: '',
        img_title: 'test_4',
        img_alt: 'test_4',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 386,
        status: 1,
        name: 'test_5',
        store_ids: [0],
        customer_group_ids: [0, 1, 4, 5, 6, 8, 9],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_5.png',
        img_url: '',
        img_title: 'test_5',
        img_alt: 'test_5',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 388,
        status: 1,
        name: 'kid_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 6, 8],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'banner.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 389,
        status: 1,
        name: 'Test_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '20210216_index_ralphLaurentBD_d.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
    ],
  },
};
const bannersMDCWithSamePos = {
  id: 1,
  name: 'homepage_hero_banner',
  status: 1,
  sort_order: 0,
  page_type: 1,
  position: 3,
  product_condition: null,
  category_ids: '',
  animation_effect: 1,
  pause_time_between_transitions: 3000,
  slide_transition_speed: 500,
  is_stop_animation_mouse_on_banner: true,
  display_arrows: true,
  display_bullets: true,
  is_random_order_image: false,
  slide_ids: [383, 384, 385, 386, 352, 387, 388, 389],
  slide_position: '{"383":"0","384":"1","389":"1","385":"1","386":"2","352":"2","387":"10","388":"12"}',
  extension_attributes: {
    image_dir: 'aw_rbslider/slides/',
    slides: [
      {
        id: 352,
        status: 1,
        name: 'test_6',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '6.jpg',
        img_url: '',
        img_title: 'test_6',
        img_alt: 'test_6',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 383,
        status: 1,
        name: 'test_2',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_2.png',
        img_url: '',
        img_title: 'test_2',
        img_alt: 'test_2',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 384,
        status: 1,
        name: 'test_3',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_3.png',
        img_url: '',
        img_title: 'test_3',
        img_alt: 'test_3',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 385,
        status: 1,
        name: 'test_4',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_4.png',
        img_url: '',
        img_title: 'test_4',
        img_alt: 'test_4',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 386,
        status: 1,
        name: 'test_5',
        store_ids: [0],
        customer_group_ids: [0, 1, 4, 5, 6, 8, 9],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_5.png',
        img_url: '',
        img_title: 'test_5',
        img_alt: 'test_5',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 388,
        status: 1,
        name: 'kid_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 6, 8],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'banner.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 389,
        status: 1,
        name: 'Test_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '20210216_index_ralphLaurentBD_d.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
    ],
  },
};

const bannersMDCWithSamePosSorted = {
  id: 1,
  name: 'homepage_hero_banner',
  status: 1,
  sort_order: 0,
  page_type: 1,
  position: 3,
  product_condition: null,
  category_ids: '',
  animation_effect: 1,
  pause_time_between_transitions: 3000,
  slide_transition_speed: 500,
  is_stop_animation_mouse_on_banner: true,
  display_arrows: true,
  display_bullets: true,
  is_random_order_image: false,
  slide_ids: [383, 384, 385, 389, 352, 386, 388],
  slide_position: '{"352":"4","383":"0","384":"1","385":"2","386":"5","388":"6","389":"3"}',
  extension_attributes: {
    image_dir: 'aw_rbslider/slides/',
    slides: [
      {
        id: 383,
        status: 1,
        name: 'test_2',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_2.png',
        img_url: '',
        img_title: 'test_2',
        img_alt: 'test_2',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 384,
        status: 1,
        name: 'test_3',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_3.png',
        img_url: '',
        img_title: 'test_3',
        img_alt: 'test_3',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 385,
        status: 1,
        name: 'test_4',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_4.png',
        img_url: '',
        img_title: 'test_4',
        img_alt: 'test_4',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 389,
        status: 1,
        name: 'Test_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '20210216_index_ralphLaurentBD_d.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 352,
        status: 1,
        name: 'test_6',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '6.jpg',
        img_url: '',
        img_title: 'test_6',
        img_alt: 'test_6',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 386,
        status: 1,
        name: 'test_5',
        store_ids: [0],
        customer_group_ids: [0, 1, 4, 5, 6, 8, 9],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_5.png',
        img_url: '',
        img_title: 'test_5',
        img_alt: 'test_5',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 388,
        status: 1,
        name: 'kid_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 6, 8],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'banner.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
    ],
  },
};

const bannersMDC = {
  id: 1,
  name: 'homepage_hero_banner',
  status: 1,
  sort_order: 0,
  page_type: 1,
  position: 3,
  product_condition: null,
  category_ids: '',
  animation_effect: 1,
  pause_time_between_transitions: 3000,
  slide_transition_speed: 500,
  is_stop_animation_mouse_on_banner: true,
  display_arrows: true,
  display_bullets: true,
  is_random_order_image: false,
  slide_ids: [344, 351, 383, 384, 385, 386, 352, 387, 388, 389],
  slide_position:
    '{"344":"0","351":"1","383":"3","384":"4","385":"5","386":"6","352":"2","387":"7","388":"8","389":"9"}',
  extension_attributes: {
    image_dir: 'aw_rbslider/slides/',
    slides: [
      {
        id: 352,
        status: 1,
        name: 'test_6',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '6.jpg',
        img_url: '',
        img_title: 'test_6',
        img_alt: 'test_6',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 383,
        status: 1,
        name: 'test_2',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_2.png',
        img_url: '',
        img_title: 'test_2',
        img_alt: 'test_2',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 384,
        status: 1,
        name: 'test_3',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_3.png',
        img_url: '',
        img_title: 'test_3',
        img_alt: 'test_3',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 385,
        status: 1,
        name: 'test_4',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_4.png',
        img_url: '',
        img_title: 'test_4',
        img_alt: 'test_4',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 386,
        status: 1,
        name: 'test_5',
        store_ids: [0],
        customer_group_ids: [0, 1, 4, 5, 6, 8, 9],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_5.png',
        img_url: '',
        img_title: 'test_5',
        img_alt: 'test_5',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 388,
        status: 1,
        name: 'kid_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 6, 8],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'banner.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 389,
        status: 1,
        name: 'Test_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '20210216_index_ralphLaurentBD_d.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
    ],
  },
};
const keysMock = ['344', '351', '352', '383', '384', '385', '386', '387', '388', '389'];
const sortedBannerMock = {
  id: 1,
  name: 'homepage_hero_banner',
  status: 1,
  sort_order: 0,
  page_type: 1,
  position: 3,
  product_condition: null,
  category_ids: '',
  animation_effect: 1,
  pause_time_between_transitions: 3000,
  slide_transition_speed: 500,
  is_stop_animation_mouse_on_banner: true,
  display_arrows: true,
  display_bullets: true,
  is_random_order_image: false,
  slide_ids: [352, 383, 384, 385, 386, 388, 389],
  slide_position: '{"352":"0","383":"1","384":"2","385":"3","386":"4","388":"5","389":"6"}',
  extension_attributes: {
    image_dir: 'aw_rbslider/slides/',
    slides: [
      {
        id: 352,
        status: 1,
        name: 'test_6',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '6.jpg',
        img_url: '',
        img_title: 'test_6',
        img_alt: 'test_6',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 383,
        status: 1,
        name: 'test_2',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_2.png',
        img_url: '',
        img_title: 'test_2',
        img_alt: 'test_2',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 384,
        status: 1,
        name: 'test_3',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_3.png',
        img_url: '',
        img_title: 'test_3',
        img_alt: 'test_3',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 385,
        status: 1,
        name: 'test_4',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_4.png',
        img_url: '',
        img_title: 'test_4',
        img_alt: 'test_4',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 386,
        status: 1,
        name: 'test_5',
        store_ids: [0],
        customer_group_ids: [0, 1, 4, 5, 6, 8, 9],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'Untitled_5.png',
        img_url: '',
        img_title: 'test_5',
        img_alt: 'test_5',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 388,
        status: 1,
        name: 'kid_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 6, 8],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: 'banner.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
      {
        id: 389,
        status: 1,
        name: 'Test_banner',
        store_ids: [0],
        customer_group_ids: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11],
        customer_segment_ids: [],
        display_from: null,
        display_to: null,
        img_type: 1,
        img_file: '20210216_index_ralphLaurentBD_d.jpg',
        img_url: '',
        img_title: '',
        img_alt: '',
        url: '',
        is_open_url_in_new_window: true,
        is_add_nofollow_to_url: true,
        banner_ids: [1],
        extension_attributes: {
          cms_position: 'TOP_LEFT',
          sku: [],
        },
      },
    ],
  },
};

export { bannersRandomMDC, bannersMDC, keysMock, sortedBannerMock, bannersMDCWithSamePos, bannersMDCWithSamePosSorted };
