export const mockSuggestSearchResult = {
  products: [
    {
      id: '48131',
      type: 'simple',
      name: 'แถม - CLINIQUE Hydration Concern Kit',
      sku: 'CDS12686285',
      urlKey: 'zero-get-free-clinique-hydration-concern-kit-cds12686285',
      overlayImageUrl: null,
      thumbnailUrl: 'https://staging-mdc.central.co.th/media/catalog/product/C/D/CDS12686285.jpg',
      brand: null,
      priceSummary: {
        original: 431,
        final: 431,
        discount: null,
      },
    },
  ],
  categories: [
    {
      id: '3055',
      name: 'บ้าน',
      parentId: '260',
      urlPath: 'home',
      isGtm: null,
    },
  ],
};

export const mockSuggestSearchCSResult = {
  products: [
    {
      suggest_promotions: [
        {
          promotion_name: 'test',
          full_condition: 'test',
          start_datetime: '2020-08-18',
          end_datetime: 'true',
          label: 'sep-mega-sale OOS',
          short_description: 'test',
        },
      ],
      configurable_products: null,
      shipping_delivery_methods: null,
      configurable_product_options: null,
      id: '48131',
      sku: 'CDS12686285',
      name: 'แถม - CLINIQUE Hydration Concern Kit',
      price: 431,
      breadcrumbs: null,
      categories: [
        {
          parent_id: null,
          id: '6900',
          name: null,
          url_path: null,
        },
      ],
      status: 1,
      visibility: '4',
      type_id: 'simple',
      created_at: '2018-08-14 14:34:58',
      configurable_product_links: null,
      brand_id: null,
      brand_name: null,
      brand_url: null,
      description: 'แถม - CLINIQUE Hydration Concern Kit จำนวน 4 ชิ้น',
      short_description: null,
      color_shade_name: null,
      color_group_name: null,
      image: '/C/D/CDS12686285.jpg',
      url_key: 'zero-get-free-clinique-hydration-concern-kit-cds12686285',
      special_price: null,
      special_from_date: null,
      special_to_date: null,
      is_in_stock: true,
      new_tag: null,
      only_at_tag: null,
      promo_tag: null,
      recommended: null,
      flash_deal: null,
      best_sellers: null,
      discount_amount: null,
      updated_at: '2019-06-25 13:00:40',
      product_type: null,
      preorder_shipping_date: null,
      max_sale_qty: 10000,
      min_sale_qty: 1,
      collection: null,
      online_exclusive_tag: null,
      marketplace_product_type_option: null,
      marketplace_seller_option: null,
      flash_deal_enable: null,
      flash_deal_qty: null,
      flash_deal_sold_qty: null,
      flash_deal_from: null,
      flash_deal_to: null,
      is_hide_original_price: null,
      is_show_special_product_name: null,
      overlay: null,
      ranking: null,
      flash_deal_position: null,
      recommened_sort_order: null,
      manual_boosting: null,
      size: '65 ซม.',
      car_seat_age: null,
      pm25: null,
      pacifier_size: null,
      watt: null,
      bottle_size: null,
      milk_powder_formula: null,
      milk_powder_type: null,
      diaper_weight: null,
      diaper_size: null,
      age_range: null,
      kid_diaper_type: null,
      cordless: null,
      anti_calc_clean: null,
      app_connected: null,
      inverter_type: null,
      grill_mode: null,
      boil_function: null,
      ro: null,
      wireless: null,
      microphone: null,
      battery_time: null,
      btu: null,
      capacity_lts: null,
      capacity_grams: null,
      digital_manual: null,
      coffee_maker_technology: null,
      filtrations: null,
      battery_type: null,
      luggage_size: null,
      weight_kg: null,
      racket: null,
      necklace_size: null,
      shoe_material: null,
      dress_length: null,
      density: null,
      bracelet_size: null,
      clothing_size: null,
      shoe_size: null,
      gender: null,
      filtration: null,
      material_clothing: null,
      material_general: null,
      sets: null,
      home_clock_type: null,
      descaling_system: null,
      material_dial: null,
      fashion_heel_type: null,
      inverter: null,
      accessory_jewelry_type: null,
      life_luggage_type: null,
      fashion_neckline: null,
      fashion_occasion: null,
      fashion_pant_fit: null,
      pattern: null,
      fashion_shoes_type: null,
      fashion_sleeves_level: null,
      fashion_socks_type: null,
      style_general: null,
      fashion_swimwear_type: null,
      fashion_underwear_type: null,
      waterproof: null,
      allow_cc: null,
      allow_cod: null,
      allow_express: null,
      allow_gift_wrapping: null,
      allow_installment: null,
      allow_return: null,
      amxnotif_hide_alert: null,
      backorders: 0,
      bu: 'CDS',
      category_ids: [6900],
      central_url_generator_flag: null,
      cmpgn: null,
      color: null,
      color_shade_id: null,
      content_status: null,
      copywrite_status: null,
      CorrelationId: '94d77295-ebd4-4734-bed4-b82340d396ac',
      enable_qty_increments: false,
      gift_message_available: null,
      gift_wrapping_available: null,
      has_options: '0',
      installment_plans: null,
      is_decimal_divided: false,
      is_jda: null,
      is_limited: null,
      is_migrated: null,
      is_qty_decimal: false,
      is_returnable: '2',
      is_sets: null,
      is_travel: null,
      jda_discount_code: null,
      low_stock_date: '2018-09-17 09:55:51',
      meta_description: null,
      meta_keyword: null,
      meta_title: null,
      homepage_new: null,
      manage_stock: true,
      min_qty: 0,
      msrp_display_actual_price_type: null,
      notify_stock_qty: 1,
      online_price_enabled: null,
      options_container: 'Block after Info Column',
      page_layout: null,
      payment_methods:
        "['Pay by Installment  ', 'บัตรเครดิต', 'ชำระเงินปลายทาง', 'PayPal Billing Agreement', 'โอนเงินผ่านธนาคาร / เคาน์เตอร์เซอร์วิส', 'บัตรเครดิต (ชำระเต็มจำนวน)']",
      photo_status: null,
      product_id: 48131,
      product_links: [],
      product_sell_type: null,
      product_status: null,
      qty_increments: 0,
      required_options: '0',
      sell_on_jd: null,
      shipping_methods: null,
      show_default_notification_message: false,
      size_type: null,
      small_image: '/C/D/CDS12686285.jpg',
      specification_from_date: null,
      stock_id: 1,
      stock_status_changed_auto: 0,
      store: null,
      store_local: null,
      t1c_earn_points_estimate: [18],
      t1c_redeemable_points: [3448],
      tax_class_id: 'Taxable Goods',
      thumbnail: '/C/D/CDS12686285.jpg',
      use_config_backorders: true,
      use_config_enable_qty_inc: true,
      use_config_manage_stock: true,
      use_config_max_sale_qty: true,
      use_config_min_qty: true,
      use_config_min_sale_qty: 1,
      use_config_notify_stock_qty: true,
      use_config_qty_increments: true,
      vat: null,
      website_ids: [1],
      media_gallery_entries: [
        {
          id: '129795',
          types: ['image', 'small_image', 'thumbnail'],
          file: '/C/D/CDS12686285.jpg',
          media_type: 'image',
          label: true,
          position: '1',
          disabled: false,
        },
      ],
      marketplace: null,
      dimension: null,
      extension_attributes_installment_plans: null,
      category_paths: [
        {
          parent_id: '6895',
          category_id: '6900',
          name: null,
          level: '3',
        },
      ],
      overall_rating: {
        rating_id: true,
        rating: 1,
        category: 'true',
        option_id: true,
        total_vote: 0,
        five_star: 0,
        four_star: 0,
        three_star: 0,
        two_star: 0,
        one_star: 0,
      },
      reviews: [],
      brand: null,
    },
  ],
  categories: [
    {
      id: '5451',
      name: 'root',
      parent_id: '260',
      url_path: 'root',
      is_gtm: null,
    },
    {
      id: '3055',
      name: 'บ้าน',
      parent_id: '260',
      url_path: 'home',
      is_gtm: null,
    },
    {
      id: '5728',
      name: 'home',
      parent_id: '5451',
      url_path: 'root/home',
      is_gtm: null,
    },
  ],
};

export const mockSearchSuggestionTermsResult = ['converse รองเท้า', 'converse'];

export const mockSearchSuggestionTermsDataLakeResult = ['converse รองเท้า', 'converse', 'converse กระเป๋าเป้'];

export const mockSearchTrendingTermsResult = ['Dyson'];

export const mockSearchTrendingTermsDataLakeResult = ['Dyson', 'Kiehl', 'Philips'];

export const mockSearchKeywordSuggestionElasticSearchResult = {
  took: 4,
  timed_out: false,
  _shards: {
    total: 3,
    successful: 3,
    skipped: 0,
    failed: 0,
  },
  hits: {
    total: {
      value: 0,
      relation: 'eq',
    },
    max_score: null,
    hits: [],
  },
  suggest: {
    'tag-suggest': [
      {
        text: 'ผู้',
        offset: 0,
        length: 3,
        options: [
          {
            text: 'ผู้หญิง Clothing Tops',
            _index: 'cds_v3_category',
            _type: '_doc',
            _id: 'CAT3314',
            _score: 57885.0,
            contexts: {
              context: ['category'],
            },
          },
          {
            text: 'ผู้หญิง Clothing ชุดชั้นใน',
            _index: 'cds_v3_category',
            _type: '_doc',
            _id: 'CAT3347',
            _score: 56124.0,
            contexts: {
              context: ['category'],
            },
          },
          {
            text: 'ผู้หญิง ช้อปตามโอกาส ชุดลำลอง',
            _index: 'cds_v3_category',
            _type: '_doc',
            _id: 'CAT3214',
            _score: 53246.0,
            contexts: {
              context: ['category'],
            },
          },
        ],
      },
    ],
  },
};

export const mockSearchKeywordSuggestionResult = [
  'ผู้หญิง Clothing Tops',
  'ผู้หญิง Clothing ชุดชั้นใน',
  'ผู้หญิง ช้อปตามโอกาส ชุดลำลอง',
];
