import { ICard, ICardType, IConsentType, IPaymentServiceKey } from '../../../types/graphql';
import { CardResponse } from '../../../dataSource/payment/PaymentDataSource';
import { DateTime } from 'luxon';

const mockCustomer = {
  id: '1',
};

const mockCartTotal = {
  base_grand_total: 9000,
};

const mockPaymentOffline = {
  isSuccess: true,
  responseCode: 'code',
  key: 'key',
  detail: {
    orderId: '804744',
  },
};

const mockPaymentDataResultCashOnDelivery = {
  paymentInput: {
    payment_method: {
      method: 'cashondelivery',
      extension_attributes: {
        card_issuer: '',
        channel: '',
        request_tax_invoice: false,
      },
      additional_data: {
        use_redirect: false,
      },
    },
    billing_address: {
      firstname: 'TEst',
      lastname: 'Testnaja',
      city: 'N/A',
      telephone: '0863213123',
      country_id: 'TH',
      street: ['N/A'],
      vat_id: null,
      company: 'N/A',
      region_id: '534',
      postcode: '10500',
      region_code: 'bkk',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
  },
  paymentServicePaymentType: undefined,
  isBankTransfer: false,
  isDolfin: false,
  customer: null,
};

const mockPaymentDataResultBankTransfer = {
  paymentInput: {
    payment_method: {
      method: 'payment_service_bank_transfer',
      extension_attributes: {
        card_issuer: '',
        channel: '',
        request_tax_invoice: false,
      },
      additional_data: {
        use_redirect: true,
      },
    },
    billing_address: {
      firstname: 'TEst',
      lastname: 'Testnaja',
      city: 'N/A',
      telephone: '0863213123',
      country_id: 'TH',
      street: ['N/A'],
      vat_id: null,
      company: 'N/A',
      region_id: '534',
      postcode: '10500',
      region_code: 'bkk',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
  },
  paymentServicePaymentType: 'bank-transfer',
  isBankTransfer: true,
  isDolfin: false,
  customer: {
    id: '1',
  },
};

const mockPaymentDataResultCreditCard = {
  paymentInput: {
    payment_method: {
      method: 'payment_service_fullpayment',
      extension_attributes: {
        t1c_earn_card_number: '2',
      },
      additional_data: {
        use_redirect: true,
      },
    },
    billing_address: {
      firstname: 'TEst',
      lastname: 'Testnaja',
      city: 'N/A',
      telephone: '0863213123',
      country_id: 'TH',
      street: ['N/A'],
      vat_id: null,
      company: 'N/A',
      region_id: '534',
      postcode: '10500',
      region_code: 'bkk',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
  },
  paymentServicePaymentType: 'full-payment',
  isBankTransfer: false,
  isDolfin: false,
  customer: {
    id: '1',
  },
};

const inputPaymentCashOnDelivery = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'cashondelivery',
      extension_attributes: {
        card_issuer: '',
        channel: '',
        request_tax_invoice: false,
      },
    },
    billing_address: {
      firstname: 'TEst',
      lastname: 'Testnaja',
      city: 'N/A',
      telephone: '0863213123',
      country_id: 'TH',
      street: ['N/A'],
      vat_id: null,
      company: 'N/A',
      region_id: '534',
      postcode: '10500',
      region_code: 'bkk',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
  },
};

const inputPaymentBankTransfer = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'payment_service_bank_transfer',
      extension_attributes: {
        t1c_earn_card_number: null,
        customer_name: 'kawvalin nop',
        customer_email: 'silicon.ssg@gmail.com',
        customer_phone: '0863213123',
        apm_agent_code: 'KBANK',
        apm_channel_code: 'IBANKING',
      },
    },
    payment_service_methods: IPaymentServiceKey.PaymentServiceBankTransfer,
    billing_address: {
      city: 'N/A',
      vat_id: null,
      firstname: 'TEst',
      lastname: 'Testnaja',
      company: 'N/A',
      postcode: '10500',
      street: ['N/A'],
      country_id: 'TH',
      region_id: '534',
      region_code: 'bkk',
      telephone: '0863213123',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
  },
};

const inputPaymentNewCreditCard = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'payment_service_fullpayment',
      extension_attributes: {
        t1c_earn_card_number: '2',
      },
    },
    payment_service_methods: IPaymentServiceKey.PaymentServiceFullpayment,
    billing_address: {
      city: 'N/A',
      vat_id: null,
      firstname: 'TEst',
      lastname: 'Testnaja',
      company: 'N/A',
      postcode: '10500',
      street: ['N/A'],
      country_id: 'TH',
      region_id: '534',
      region_code: 'bkk',
      telephone: '0863213123',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
    card: {
      encrypted_card_data:
        '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
      is_store_card: true,
      cardholder_name: 'test',
      expiry_month: 10,
      expiry_year: 2022,
    },
  },
};

const mockPaymentInformationResult = {
  message: 'success',
  order: '804744',
  redirect_url: '/FC432200900799/e891f9f3fbd33e3f9f6a90e4ca77b2e4e5b23595',
};

const mockPaymentInformationResultBankTransfer = {
  message: 'success',
  order: '804744',
  payment_offline: mockPaymentOffline,
  redirect_url: null,
  request_form: null,
};

const mockAuthorizePaymentResult = {
  url: 'url',
  payload: {
    paymentRequest: 'payload',
  },
};

const mockAuthorizePayment = {
  formUrl: 'url',
  encryptedPayload: 'payload',
};

const mockPayloadAuthorizePaymentNewCreditCard = {
  cardId: undefined,
  cardholderName: 'test',
  customerId: '1',
  description: '',
  encryptCardData:
    '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
  expiryMonth: 10,
  expiryYear: 2022,
  is3ds: true,
  isStoreCard: true,
  orderEntityId: '804744',
};

const mockPayloadAuthorizePaymentNewCreditCardForIs3dsFalse = {
  cardId: undefined,
  cardholderName: 'test',
  customerId: '1',
  description: '',
  encryptCardData:
    '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
  expiryMonth: 10,
  expiryYear: 2022,
  is3ds: false,
  isStoreCard: true,
  orderEntityId: '804744',
};

const mockPayloadAuthorizePaymentSavedCreditCard = {
  cardId: '111',
  cardholderName: undefined,
  customerId: '1',
  description: '',
  encryptCardData:
    '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
  expiryMonth: undefined,
  expiryYear: undefined,
  is3ds: true,
  isStoreCard: undefined,
  orderEntityId: '804744',
};

const mockPayloadAuthorizePaymentSavedCreditCardNotSendOTP = {
  cardId: '111',
  cardholderName: undefined,
  customerId: '1',
  description: '',
  encryptCardData:
    '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
  expiryMonth: undefined,
  expiryYear: undefined,
  is3ds: false,
  isStoreCard: undefined,
  orderEntityId: '804744',
};

const inputPaymentCreditCardWithoutCard = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'payment_service_fullpayment',
      extension_attributes: {
        t1c_earn_card_number: '2',
      },
    },
    payment_service_methods: IPaymentServiceKey.PaymentServiceFullpayment,
    billing_address: {
      city: 'N/A',
      vat_id: null,
      firstname: 'TEst',
      lastname: 'Testnaja',
      company: 'N/A',
      postcode: '10500',
      street: ['N/A'],
      country_id: 'TH',
      region_id: '534',
      region_code: 'bkk',
      telephone: '0863213123',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
  },
};

const inputPaymentSavedCreditCard = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'payment_service_fullpayment',
      extension_attributes: {
        t1c_earn_card_number: '2',
      },
    },
    payment_service_methods: IPaymentServiceKey.PaymentServiceFullpayment,
    billing_address: {
      city: 'N/A',
      vat_id: null,
      firstname: 'TEst',
      lastname: 'Testnaja',
      company: 'N/A',
      postcode: '10500',
      street: ['N/A'],
      country_id: 'TH',
      region_id: '534',
      region_code: 'bkk',
      telephone: '0863213123',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
    saved_card: {
      card_id: '111',
      encrypted_card_data:
        '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
    },
  },
};

const inputPaymentSavedCreditCardWithoutEncryptedCard = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'payment_service_fullpayment',
      extension_attributes: {
        t1c_earn_card_number: '2',
      },
    },
    payment_service_methods: IPaymentServiceKey.PaymentServiceFullpayment,
    billing_address: {
      city: 'N/A',
      vat_id: null,
      firstname: 'TEst',
      lastname: 'Testnaja',
      company: 'N/A',
      postcode: '10500',
      street: ['N/A'],
      country_id: 'TH',
      region_id: '534',
      region_code: 'bkk',
      telephone: '0863213123',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
    saved_card: {
      card_id: '111',
      is_store_card: true,
      cardholder_name: 'test',
      expiry_month: 10,
      expiry_year: 2022,
    },
  },
};

const inputPaymentNewCreditCardWithoutStoreCard = {
  isGuest: false,
  input: {
    payment_method: {
      method: 'payment_service_fullpayment',
      extension_attributes: {
        t1c_earn_card_number: '2',
      },
    },
    payment_service_methods: IPaymentServiceKey.PaymentServiceFullpayment,
    billing_address: {
      city: 'N/A',
      vat_id: null,
      firstname: 'TEst',
      lastname: 'Testnaja',
      company: 'N/A',
      postcode: '10500',
      street: ['N/A'],
      country_id: 'TH',
      region_id: '534',
      region_code: 'bkk',
      telephone: '0863213123',
      custom_attributes: {
        address_name: 'Bang Rak',
        customer_address_type: 'shipping',
        house_no: '111/12',
        district_id: '25',
        district: 'บางรัก',
        subdistrict_id: '157',
        subdistrict: 'บางรัก',
        building_type: 'townhouse',
        lat: '13.7932141',
        lng: '100.3753413',
      },
    },
    accept_consents: [IConsentType.Privacy],
    email: 'kawvalin@central.tech',
    remark: '',
    substitution: '',
    card: {
      encrypted_card_data:
        '00acyj0XhAhMxwuB+97e6r/nhj9skGRssN9UEjJfTUMQrm0YckrKP8IIOvx6QuDHhNFURKu7IolkjTaVdtZBZd1VGRt9jt7AABImcKUZgeQnTjj8jtRAD299YubuToqLsfwuuNGAu1hK89JlHrOrBhn9ydKHu8eQiJfz4NeWFlRwpfE=U2FsdGVkX1+n7VIqcVG12e5lY4WGEom3RfQSIdjMjboL9rLTc/vr5ga07omxecmn',
      is_store_card: false,
      cardholder_name: 'test',
      expiry_month: 10,
      expiry_year: 2022,
    },
  },
};

const mockGetPaymentServiceResponse = {
  payment_service_base_url: '',
  bu_public_key: '',
  bu_secret_key: '',
  bu_store_key: '',
};

export const cardOneBeforeTransform: CardResponse = {
  id: '1',
  cardType: 'JCB',
  last4Digits: '304716',
  createdDateTime: '2020-11-05T11:10:51.790Z',
  expiryMonth: 12,
  expiryYear: 99,
  isDefault: true,
  bankId: '1',
  bankName: 'Test',
  promoCodes: ['TEST_PROMO'],
  maskPan: '304716',
};

export const cardTwoBeforeTransform: CardResponse = {
  id: '2',
  cardType: 'MasterCard',
  last4Digits: '304716',
  createdDateTime: '2020-11-05T11:10:51.790Z',
  expiryMonth: 12,
  expiryYear: 99,
  isDefault: false,
  bankId: '1',
  bankName: 'Test',
  promoCodes: [],
  maskPan: '411111',
};

export const cardThreeBeforeTransform: CardResponse = {
  id: '3',
  cardType: 'MasterCardxJCB',
  last4Digits: '304716',
  createdDateTime: '2020-11-05T11:10:51.790Z',
  expiryMonth: 12,
  expiryYear: 99,
  isDefault: null,
  bankId: '1',
  bankName: 'Test',
  promoCodes: [],
  maskPan: '411111',
};

export const cardOne: ICard = {
  id: '1',
  type: ICardType.Jcb,
  masked_number: '304716',
  created_at: DateTime.fromISO(cardOneBeforeTransform.createdDateTime, { zone: 'utc+0' }).toUTC(),
  is_default: true,
  bank_id: '1',
  bank_name: 'Test',
  promo_codes: ['TEST_PROMO'],
  expiry_month: 12,
  expiry_year: 99,
};
export const cardTwo: ICard = {
  id: '2',
  type: ICardType.MasterCard,
  masked_number: '411111',
  created_at: DateTime.fromISO(cardTwoBeforeTransform.createdDateTime, { zone: 'utc+0' }).toUTC(),
  bank_id: '1',
  bank_name: 'Test',
  promo_codes: [],
  is_default: false,
  expiry_month: 12,
  expiry_year: 99,
};

export const cardThree: ICard = {
  id: '3',
  type: ICardType.Others,
  masked_number: '411111',
  created_at:  DateTime.fromISO(cardThreeBeforeTransform.createdDateTime, { zone: 'utc+0' }).toUTC(),
  bank_id: '1',
  bank_name: 'Test',
  promo_codes: [],
  is_default: false,
  expiry_month: 12,
  expiry_year: 99,
};

const mockICreditCardListWithDefaultCard: ICard[] = [cardOne, cardTwo];

const mockICreditCardListWithDefaultCardWithDescId: ICard[] = [cardTwo, cardOne];

const mockICreditCardListWithoutDefaultCard: ICard[] = [
  {
    ...cardOne,
    is_default: false,
  },
  {
    ...cardTwo,
    is_default: false,
  },
];

const mockStoreConfigResponse = [
  {
    code: 'th',
    base_url: 'localhost',
    secure_base_url: 'https://localhost',
    base_media_url: 'localhost/media',
  },
];

const mockRepaymentResponse = {
  message: 'success',
  order: 'FC432201217928',
  redirect_url: null,
  request_form: null,
};

const mockOrderResponse = {
  items: [
    {
      applied_rule_ids: '',
      base_currency_code: '',
      base_discount_amount: 0,
      base_grand_total: 0,
      base_discount_tax_compensation_amount: 0,
      base_shipping_amount: 0,
      base_shipping_discount_amount: 0,
      base_shipping_discount_tax_compensation_amnt: 0,
      base_shipping_incl_tax: 0,
      base_shipping_tax_amount: 0,
      base_subtotal: 0,
      base_subtotal_incl_tax: 0,
      base_tax_amount: 0,
      base_total_due: 0,
      base_to_global_rate: 0,
      base_to_order_rate: 0,
      billing_address_id: 0,
      created_at: '',
      customer_email: '',
      customer_firstname: '',
      customer_group_id: 0,
      customer_id: 0,
      customer_is_guest: 0,
      customer_lastname: '',
      customer_note_notify: 0,
      discount_amount: 0,
      entity_id: 0,
      global_currency_code: '',
      grand_total: 0,
      discount_tax_compensation_amount: 0,
      increment_id: '',
      is_virtual: 0,
      order_currency_code: '',
      protect_code: '',
      quote_id: 0,
      remote_ip: '',
      shipping_amount: 0,
      shipping_description: '',
      shipping_discount_amount: 0,
      shipping_discount_tax_compensation_amount: 0,
      shipping_incl_tax: 0,
      shipping_tax_amount: 0,
      state: '',
      status: '',
      store_currency_code: '',
      store_id: 0,
      store_name: '',
      store_to_base_rate: 0,
      store_to_order_rate: 0,
      subtotal: 0,
      subtotal_incl_tax: 0,
      tax_amount: 0,
      total_due: 0,
      total_item_count: 0,
      total_qty_ordered: 0,
      updated_at: '',
      weight: 0,
      x_forwarded_for: '',
      items: [],
      billing_address: {
        address_type: '',
        city: '',
        country_id: '',
        email: '',
        entity_id: 0,
        firstname: '',
        lastname: '',
        parent_id: 0,
        postcode: '',
        region: '',
        region_code: '',
        region_id: 0,
        street: [],
        telephone: '',
        extension_attributes: {
          custom_attributes: [
            {
              attribute_code: '',
              value: '',
            },
          ],
        },
      },
      payment: {
        account_status: null,
        additional_information: [],
        amount_authorized: 0,
        amount_ordered: 0,
        base_amount_authorized: 0,
        base_amount_ordered: 0,
        base_shipping_amount: 0,
        cc_exp_year: '',
        cc_last4: null,
        cc_ss_start_month: '',
        cc_ss_start_year: '',
        entity_id: 0,
        last_trans_id: '',
        method: '',
        parent_id: 0,
        shipping_amount: 0,
      },
      status_histories: [
        {
          comment: '',
          created_at: '',
          entity_id: 0,
          entity_name: '',
          is_customer_notified: 0,
          is_visible_on_front: 0,
          parent_id: 0,
          status: '',
        },
      ],
      extension_attributes: {
        order_children_items: null,
        order_children_ids: null,
        shipping_assignments: [],
        payment_additional_info: [],
        applied_taxes: [],
        item_applied_taxes: [],
        converting_from_quote: true,
        gift_cards: [],
        base_gift_cards_amount: 0,
        gift_cards_amount: 0,
        gw_base_price: '',
        gw_price: '',
        gw_items_base_price: '',
        gw_items_price: '',
        gw_card_base_price: '',
        gw_card_price: '',
        mom_status_reason: '',
        payment_method_label: '',
        base_surcharge_fee_amount: 0,
        surcharge_fee_amount: 0,
        order_status: 'awaiting_payment',
        p2c2p_promotion_code: '',
        shipping_method_label: '',
        delivery_status: '',
        gw_id: '',
        gw_price_incl_tax: '',
        credit_card_on_top_discount_amount: 0,
        t1c_redeem: {
          points_redeem: '',
          points_total: '',
          discount_amount: '',
          discount_amount_formatted: '',
        },
        coupons_applied: [],
        pickup_code: null,
      },
    },
  ],
  search_criteria: {
    filter_groups: [],
  },
  total_count: 1,
};

const mockOrderResponseWithTotalGreaterThan10000 = {
  items: [
    {
      applied_rule_ids: '',
      base_currency_code: '',
      base_discount_amount: 0,
      base_grand_total: 20000,
      base_discount_tax_compensation_amount: 0,
      base_shipping_amount: 0,
      base_shipping_discount_amount: 0,
      base_shipping_discount_tax_compensation_amnt: 0,
      base_shipping_incl_tax: 0,
      base_shipping_tax_amount: 0,
      base_subtotal: 0,
      base_subtotal_incl_tax: 0,
      base_tax_amount: 0,
      base_total_due: 0,
      base_to_global_rate: 0,
      base_to_order_rate: 0,
      billing_address_id: 0,
      created_at: '',
      customer_email: '',
      customer_firstname: '',
      customer_group_id: 0,
      customer_id: 0,
      customer_is_guest: 0,
      customer_lastname: '',
      customer_note_notify: 0,
      discount_amount: 0,
      entity_id: 0,
      global_currency_code: '',
      grand_total: 0,
      discount_tax_compensation_amount: 0,
      increment_id: '',
      is_virtual: 0,
      order_currency_code: '',
      protect_code: '',
      quote_id: 0,
      remote_ip: '',
      shipping_amount: 0,
      shipping_description: '',
      shipping_discount_amount: 0,
      shipping_discount_tax_compensation_amount: 0,
      shipping_incl_tax: 0,
      shipping_tax_amount: 0,
      state: '',
      status: '',
      store_currency_code: '',
      store_id: 0,
      store_name: '',
      store_to_base_rate: 0,
      store_to_order_rate: 0,
      subtotal: 0,
      subtotal_incl_tax: 0,
      tax_amount: 0,
      total_due: 0,
      total_item_count: 0,
      total_qty_ordered: 0,
      updated_at: '',
      weight: 0,
      x_forwarded_for: '',
      items: [],
      billing_address: {
        address_type: '',
        city: '',
        country_id: '',
        email: '',
        entity_id: 0,
        firstname: '',
        lastname: '',
        parent_id: 0,
        postcode: '',
        region: '',
        region_code: '',
        region_id: 0,
        street: [],
        telephone: '',
        extension_attributes: {
          custom_attributes: [
            {
              attribute_code: '',
              value: '',
            },
          ],
        },
      },
      payment: {
        account_status: null,
        additional_information: [],
        amount_authorized: 0,
        amount_ordered: 0,
        base_amount_authorized: 0,
        base_amount_ordered: 0,
        base_shipping_amount: 0,
        cc_exp_year: '',
        cc_last4: null,
        cc_ss_start_month: '',
        cc_ss_start_year: '',
        entity_id: 0,
        last_trans_id: '',
        method: '',
        parent_id: 0,
        shipping_amount: 0,
      },
      status_histories: [
        {
          comment: '',
          created_at: '',
          entity_id: 0,
          entity_name: '',
          is_customer_notified: 0,
          is_visible_on_front: 0,
          parent_id: 0,
          status: '',
        },
      ],
      extension_attributes: {
        order_children_items: null,
        order_children_ids: null,
        shipping_assignments: [],
        payment_additional_info: [],
        applied_taxes: [],
        item_applied_taxes: [],
        converting_from_quote: true,
        gift_cards: [],
        base_gift_cards_amount: 0,
        gift_cards_amount: 0,
        gw_base_price: '',
        gw_price: '',
        gw_items_base_price: '',
        gw_items_price: '',
        gw_card_base_price: '',
        gw_card_price: '',
        mom_status_reason: '',
        payment_method_label: '',
        base_surcharge_fee_amount: 0,
        surcharge_fee_amount: 0,
        order_status: 'awaiting_payment',
        p2c2p_promotion_code: '',
        shipping_method_label: '',
        delivery_status: '',
        gw_id: '',
        gw_price_incl_tax: '',
        credit_card_on_top_discount_amount: 0,
        t1c_redeem: {
          points_redeem: '',
          points_total: '',
          discount_amount: '',
          discount_amount_formatted: '',
        },
        coupons_applied: [],
        pickup_code: null,
      },
    },
  ],
  search_criteria: {
    filter_groups: [],
  },
  total_count: 1,
};

const mockOrderResponseWithCancel = {
  items: [
    {
      applied_rule_ids: '',
      base_currency_code: '',
      base_discount_amount: 0,
      base_grand_total: 0,
      base_discount_tax_compensation_amount: 0,
      base_shipping_amount: 0,
      base_shipping_discount_amount: 0,
      base_shipping_discount_tax_compensation_amnt: 0,
      base_shipping_incl_tax: 0,
      base_shipping_tax_amount: 0,
      base_subtotal: 0,
      base_subtotal_incl_tax: 0,
      base_tax_amount: 0,
      base_total_due: 0,
      base_to_global_rate: 0,
      base_to_order_rate: 0,
      billing_address_id: 0,
      created_at: '',
      customer_email: '',
      customer_firstname: '',
      customer_group_id: 0,
      customer_id: 0,
      customer_is_guest: 0,
      customer_lastname: '',
      customer_note_notify: 0,
      discount_amount: 0,
      entity_id: 0,
      global_currency_code: '',
      grand_total: 0,
      discount_tax_compensation_amount: 0,
      increment_id: '',
      is_virtual: 0,
      order_currency_code: '',
      protect_code: '',
      quote_id: 0,
      remote_ip: '',
      shipping_amount: 0,
      shipping_description: '',
      shipping_discount_amount: 0,
      shipping_discount_tax_compensation_amount: 0,
      shipping_incl_tax: 0,
      shipping_tax_amount: 0,
      state: '',
      status: '',
      store_currency_code: '',
      store_id: 0,
      store_name: '',
      store_to_base_rate: 0,
      store_to_order_rate: 0,
      subtotal: 0,
      subtotal_incl_tax: 0,
      tax_amount: 0,
      total_due: 0,
      total_item_count: 0,
      total_qty_ordered: 0,
      updated_at: '',
      weight: 0,
      x_forwarded_for: '',
      items: [],
      billing_address: {
        address_type: '',
        city: '',
        country_id: '',
        email: '',
        entity_id: 0,
        firstname: '',
        lastname: '',
        parent_id: 0,
        postcode: '',
        region: '',
        region_code: '',
        region_id: 0,
        street: [],
        telephone: '',
        extension_attributes: {
          custom_attributes: [
            {
              attribute_code: '',
              value: '',
            },
          ],
        },
      },
      payment: {
        account_status: null,
        additional_information: [],
        amount_authorized: 0,
        amount_ordered: 0,
        base_amount_authorized: 0,
        base_amount_ordered: 0,
        base_shipping_amount: 0,
        cc_exp_year: '',
        cc_last4: null,
        cc_ss_start_month: '',
        cc_ss_start_year: '',
        entity_id: 0,
        last_trans_id: '',
        method: '',
        parent_id: 0,
        shipping_amount: 0,
      },
      status_histories: [
        {
          comment: '',
          created_at: '',
          entity_id: 0,
          entity_name: '',
          is_customer_notified: 0,
          is_visible_on_front: 0,
          parent_id: 0,
          status: '',
        },
      ],
      extension_attributes: {
        order_children_items: null,
        order_children_ids: null,
        shipping_assignments: [],
        payment_additional_info: [],
        applied_taxes: [],
        item_applied_taxes: [],
        converting_from_quote: true,
        gift_cards: [],
        base_gift_cards_amount: 0,
        gift_cards_amount: 0,
        gw_base_price: '',
        gw_price: '',
        gw_items_base_price: '',
        gw_items_price: '',
        gw_card_base_price: '',
        gw_card_price: '',
        mom_status_reason: '',
        payment_method_label: '',
        base_surcharge_fee_amount: 0,
        surcharge_fee_amount: 0,
        order_status: 'cancel',
        p2c2p_promotion_code: '',
        shipping_method_label: '',
        delivery_status: '',
        gw_id: '',
        gw_price_incl_tax: '',
        credit_card_on_top_discount_amount: 0,
        t1c_redeem: {
          points_redeem: '',
          points_total: '',
          discount_amount: '',
          discount_amount_formatted: '',
        },
        coupons_applied: [],
      },
    },
  ],
  search_criteria: {
    filter_groups: [],
  },
  total_count: 1,
};

const mockOrderResponseWithMCOMOnHoldStatus = {
  items: [
    {
      applied_rule_ids: '',
      base_currency_code: '',
      base_discount_amount: 0,
      base_grand_total: 0,
      base_discount_tax_compensation_amount: 0,
      base_shipping_amount: 0,
      base_shipping_discount_amount: 0,
      base_shipping_discount_tax_compensation_amnt: 0,
      base_shipping_incl_tax: 0,
      base_shipping_tax_amount: 0,
      base_subtotal: 0,
      base_subtotal_incl_tax: 0,
      base_tax_amount: 0,
      base_total_due: 0,
      base_to_global_rate: 0,
      base_to_order_rate: 0,
      billing_address_id: 0,
      created_at: '',
      customer_email: '',
      customer_firstname: '',
      customer_group_id: 0,
      customer_id: 0,
      customer_is_guest: 0,
      customer_lastname: '',
      customer_note_notify: 0,
      discount_amount: 0,
      entity_id: 0,
      global_currency_code: '',
      grand_total: 0,
      discount_tax_compensation_amount: 0,
      increment_id: '',
      is_virtual: 0,
      order_currency_code: '',
      protect_code: '',
      quote_id: 0,
      remote_ip: '',
      shipping_amount: 0,
      shipping_description: '',
      shipping_discount_amount: 0,
      shipping_discount_tax_compensation_amount: 0,
      shipping_incl_tax: 0,
      shipping_tax_amount: 0,
      state: '',
      status: 'MCOM_ONHOLD',
      store_currency_code: '',
      store_id: 0,
      store_name: '',
      store_to_base_rate: 0,
      store_to_order_rate: 0,
      subtotal: 0,
      subtotal_incl_tax: 0,
      tax_amount: 0,
      total_due: 0,
      total_item_count: 0,
      total_qty_ordered: 0,
      updated_at: '',
      weight: 0,
      x_forwarded_for: '',
      items: [],
      billing_address: {
        address_type: '',
        city: '',
        country_id: '',
        email: '',
        entity_id: 0,
        firstname: '',
        lastname: '',
        parent_id: 0,
        postcode: '',
        region: '',
        region_code: '',
        region_id: 0,
        street: [],
        telephone: '',
        extension_attributes: {
          custom_attributes: [
            {
              attribute_code: '',
              value: '',
            },
          ],
        },
      },
      payment: {
        account_status: null,
        additional_information: [],
        amount_authorized: 0,
        amount_ordered: 0,
        base_amount_authorized: 0,
        base_amount_ordered: 0,
        base_shipping_amount: 0,
        cc_exp_year: '',
        cc_last4: null,
        cc_ss_start_month: '',
        cc_ss_start_year: '',
        entity_id: 0,
        last_trans_id: '',
        method: '',
        parent_id: 0,
        shipping_amount: 0,
      },
      status_histories: [
        {
          comment: '',
          created_at: '',
          entity_id: 0,
          entity_name: '',
          is_customer_notified: 0,
          is_visible_on_front: 0,
          parent_id: 0,
          status: '',
        },
      ],
      extension_attributes: {
        order_children_items: null,
        order_children_ids: null,
        shipping_assignments: [],
        payment_additional_info: [],
        applied_taxes: [],
        item_applied_taxes: [],
        converting_from_quote: true,
        gift_cards: [],
        base_gift_cards_amount: 0,
        gift_cards_amount: 0,
        gw_base_price: '',
        gw_price: '',
        gw_items_base_price: '',
        gw_items_price: '',
        gw_card_base_price: '',
        gw_card_price: '',
        mom_status_reason: '',
        payment_method_label: '',
        base_surcharge_fee_amount: 0,
        surcharge_fee_amount: 0,
        order_status: '',
        p2c2p_promotion_code: '',
        shipping_method_label: '',
        delivery_status: '',
        gw_id: '',
        gw_price_incl_tax: '',
        credit_card_on_top_discount_amount: 0,
        t1c_redeem: {
          points_redeem: '',
          points_total: '',
          discount_amount: '',
          discount_amount_formatted: '',
        },
        coupons_applied: [],
      },
    },
  ],
  search_criteria: {
    filter_groups: [],
  },
  total_count: 1,
};

const mockOrderResponseWithEmptyItem = {
  items: [],
  search_criteria: {
    filter_groups: [],
  },
  total_count: 1,
};

const mockOrderResponseWithOfflinePayment = {
  items: [
    {
      applied_rule_ids: '',
      base_currency_code: '',
      base_discount_amount: 0,
      base_grand_total: 0,
      base_discount_tax_compensation_amount: 0,
      base_shipping_amount: 0,
      base_shipping_discount_amount: 0,
      base_shipping_discount_tax_compensation_amnt: 0,
      base_shipping_incl_tax: 0,
      base_shipping_tax_amount: 0,
      base_subtotal: 0,
      base_subtotal_incl_tax: 0,
      base_tax_amount: 0,
      base_total_due: 0,
      base_to_global_rate: 0,
      base_to_order_rate: 0,
      billing_address_id: 0,
      created_at: '',
      customer_email: '',
      customer_firstname: '',
      customer_group_id: 0,
      customer_id: 0,
      customer_is_guest: 0,
      customer_lastname: '',
      customer_note_notify: 0,
      discount_amount: 0,
      entity_id: 0,
      global_currency_code: '',
      grand_total: 0,
      discount_tax_compensation_amount: 0,
      increment_id: '',
      is_virtual: 0,
      order_currency_code: '',
      protect_code: '',
      quote_id: 0,
      remote_ip: '',
      shipping_amount: 0,
      shipping_description: '',
      shipping_discount_amount: 0,
      shipping_discount_tax_compensation_amount: 0,
      shipping_incl_tax: 0,
      shipping_tax_amount: 0,
      state: '',
      status: '',
      store_currency_code: '',
      store_id: 0,
      store_name: '',
      store_to_base_rate: 0,
      store_to_order_rate: 0,
      subtotal: 0,
      subtotal_incl_tax: 0,
      tax_amount: 0,
      total_due: 0,
      total_item_count: 0,
      total_qty_ordered: 0,
      updated_at: '',
      weight: 0,
      x_forwarded_for: '',
      items: [],
      billing_address: {
        address_type: '',
        city: '',
        country_id: '',
        email: '',
        entity_id: 0,
        firstname: '',
        lastname: '',
        parent_id: 0,
        postcode: '',
        region: '',
        region_code: '',
        region_id: 0,
        street: [],
        telephone: '',
        extension_attributes: {
          custom_attributes: [
            {
              attribute_code: '',
              value: '',
            },
          ],
        },
      },
      payment: {
        account_status: null,
        additional_information: [],
        amount_authorized: 0,
        amount_ordered: 0,
        base_amount_authorized: 0,
        base_amount_ordered: 0,
        base_shipping_amount: 0,
        cc_exp_year: '',
        cc_last4: null,
        cc_ss_start_month: '',
        cc_ss_start_year: '',
        entity_id: 0,
        last_trans_id: '',
        method: 'payment_service_bank_transfer',
        parent_id: 0,
        shipping_amount: 0,
      },
      status_histories: [
        {
          comment: '',
          created_at: '',
          entity_id: 0,
          entity_name: '',
          is_customer_notified: 0,
          is_visible_on_front: 0,
          parent_id: 0,
          status: '',
        },
      ],
      extension_attributes: {
        order_children_items: null,
        order_children_ids: null,
        shipping_assignments: [],
        payment_additional_info: [],
        applied_taxes: [],
        item_applied_taxes: [],
        converting_from_quote: true,
        gift_cards: [],
        base_gift_cards_amount: 0,
        gift_cards_amount: 0,
        gw_base_price: '',
        gw_price: '',
        gw_items_base_price: '',
        gw_items_price: '',
        gw_card_base_price: '',
        gw_card_price: '',
        mom_status_reason: '',
        payment_method_label: '',
        base_surcharge_fee_amount: 0,
        surcharge_fee_amount: 0,
        order_status: 'awaiting_payment',
        p2c2p_promotion_code: '',
        shipping_method_label: '',
        delivery_status: '',
        gw_id: '',
        gw_price_incl_tax: '',
        credit_card_on_top_discount_amount: 0,
        t1c_redeem: {
          points_redeem: '',
          points_total: '',
          discount_amount: '',
          discount_amount_formatted: '',
        },
        coupons_applied: [],
      },
    },
  ],
  search_criteria: {
    filter_groups: [],
  },
  total_count: 1,
};

const mockIPaymentRequestForm = {
  url: 'String',
  payload: {
    paymentRequest: '',
  },
};

export {
  mockCustomer,
  mockCartTotal,
  mockPaymentOffline,
  mockAuthorizePayment,
  mockAuthorizePaymentResult,
  mockPaymentDataResultCashOnDelivery,
  mockPaymentDataResultBankTransfer,
  mockPaymentDataResultCreditCard,
  mockPayloadAuthorizePaymentNewCreditCard,
  mockPayloadAuthorizePaymentSavedCreditCard,
  mockPayloadAuthorizePaymentSavedCreditCardNotSendOTP,
  mockPayloadAuthorizePaymentNewCreditCardForIs3dsFalse,
  mockPaymentInformationResult,
  mockPaymentInformationResultBankTransfer,
  mockGetPaymentServiceResponse,
  mockICreditCardListWithDefaultCard,
  mockICreditCardListWithoutDefaultCard,
  mockStoreConfigResponse,
  inputPaymentCashOnDelivery,
  inputPaymentBankTransfer,
  inputPaymentNewCreditCard,
  inputPaymentSavedCreditCard,
  inputPaymentCreditCardWithoutCard,
  inputPaymentSavedCreditCardWithoutEncryptedCard,
  inputPaymentNewCreditCardWithoutStoreCard,
  mockICreditCardListWithDefaultCardWithDescId,
  mockRepaymentResponse,
  mockOrderResponse,
  mockIPaymentRequestForm,
  mockOrderResponseWithOfflinePayment,
  mockOrderResponseWithCancel,
  mockOrderResponseWithEmptyItem,
  mockOrderResponseWithTotalGreaterThan10000,
  mockOrderResponseWithMCOMOnHoldStatus,
};
