name: ReportPortal
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release","ReleaseDevelop"]
    types:
      - completed
jobs:
  report_portal:
    name: Report Portal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - run: yarn install
      - run: yarn workspace @central-tech/api codegen
      - run: yarn report
        env: # Or as an environment variable
          RP_ENDPOINT: ${{ secrets.RP_ENDPOINT }}
          RP_TOKEN: ${{ secrets.RP_TOKEN }}
